// Package base32 is a drop-in fast path for standard base32 (StdEncoding,
// RFC 4648, padded). The bulk of encoding runs a SIMD kernel generated by
// go-asmgen (amd64 SSE + AVX2, arm64 NEON; other arches fall back to the
// standard library), the short tail and padding use encoding/base32 so output
// is byte-identical to base32.StdEncoding.
package base32

import "encoding/base32"

// EncodedLen returns the length in bytes of the base32 encoding of n input bytes.
func EncodedLen(n int) int { return base32.StdEncoding.EncodedLen(n) }

// Encode writes the StdEncoding base32 of src into dst (len(dst) >= EncodedLen).
func Encode(dst, src []byte) {
	sd, dd := encodeSIMD(dst, src)
	base32.StdEncoding.Encode(dst[dd:], src[sd:])
}

// EncodeToString returns the StdEncoding base32 of src.
func EncodeToString(src []byte) string {
	dst := make([]byte, EncodedLen(len(src)))
	Encode(dst, src)
	return string(dst)
}

// DecodedLen returns the max decoded length of n base32 bytes.
func DecodedLen(n int) int { return base32.StdEncoding.DecodedLen(n) }

// Decode decodes StdEncoding base32 src into dst. (Scalar for now; a SIMD decode
// kernel is planned.)
func Decode(dst, src []byte) (int, error) { return base32.StdEncoding.Decode(dst, src) }

// DecodeString decodes a StdEncoding base32 string.
func DecodeString(s string) ([]byte, error) { return base32.StdEncoding.DecodeString(s) }
