// Package base32 is a drop-in fast path for standard base32 (StdEncoding,
// RFC 4648, padded). The bulk of both encoding and decoding runs a SIMD kernel
// generated by go-asmgen (amd64 SSE + AVX2, ppc64le VSX, s390x vector facility;
// other arches fall back to the standard library); the short tail, padding and
// all error reporting use encoding/base32 so output is byte-identical and errors
// are offset-identical to base32.StdEncoding.
package base32

import "encoding/base32"

// EncodedLen returns the length in bytes of the base32 encoding of n input bytes.
func EncodedLen(n int) int { return base32.StdEncoding.EncodedLen(n) }

// Encode writes the StdEncoding base32 of src into dst (len(dst) >= EncodedLen).
func Encode(dst, src []byte) {
	sd, dd := encodeSIMD(dst, src)
	base32.StdEncoding.Encode(dst[dd:], src[sd:])
}

// EncodeToString returns the StdEncoding base32 of src.
func EncodeToString(src []byte) string {
	dst := make([]byte, EncodedLen(len(src)))
	Encode(dst, src)
	return string(dst)
}

// DecodedLen returns the max decoded length of n base32 bytes.
func DecodedLen(n int) int { return base32.StdEncoding.DecodedLen(n) }

// Decode decodes StdEncoding base32 src into dst, byte-for-byte identical to
// base32.StdEncoding.Decode and with identical CorruptInputError offsets. A SIMD
// kernel decodes whole 8-char blocks of valid alphabet chars from the front; the
// remainder (the final block, any padding/tail, and everything from the first
// invalid char) is handed to encoding/base32, with the error offset shifted back
// by the SIMD-consumed prefix so it points at the same byte the stdlib would.
func Decode(dst, src []byte) (int, error) {
	sd, dd := decodeSIMD(dst, src)
	n, err := base32.StdEncoding.Decode(dst[dd:], src[sd:])
	if err != nil {
		// StdEncoding.Decode only ever returns a CorruptInputError; shift its
		// offset back over the SIMD-consumed prefix so it points at the same byte
		// the stdlib would report on the same input.
		ce := err.(base32.CorruptInputError)
		return dd + n, base32.CorruptInputError(int64(ce) + int64(sd))
	}
	return dd + n, nil
}

// DecodeString decodes a StdEncoding base32 string.
func DecodeString(s string) ([]byte, error) {
	dst := make([]byte, DecodedLen(len(s)))
	n, err := Decode(dst, []byte(s))
	return dst[:n], err
}
