//go:build arm64

package base32

// decodeBlocksNEON (8 chars -> 5 bytes, two blocks per iteration) is the
// vectorised base32 decoder for arm64 NEON. Generated by go-asmgen
// (decode_arm64_gen.go), in decode_arm64.s. It returns the number of 8-char
// blocks it actually decoded, stopping before the first block containing a
// non-alphabet char so the caller can hand the remainder (errors, padding) to
// encoding/base32. NEON is baseline on arm64, so there is no runtime dispatch.
func decodeBlocksNEON(dst, src []byte, n int) int

// decodeSIMD decodes whole 8-char blocks of valid alphabet chars from the front
// of src, leaving the final block (and anything after the first invalid char) to
// encoding/base32 so padding/tail/error semantics stay byte-and-error identical.
// Each block emits 5 bytes but VST1 writes a full 16-byte vector, so the block
// count is capped to keep the final store in bounds.
func decodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	full := len(src) / 8
	if full < 2 {
		return 0, 0
	}
	maxBlocks := full - 1 // reserve the final block for the stdlib tail
	// Cap so the last 16-byte VST1 (at dst[(maxBlocks-1)*5]) stays in bounds.
	for maxBlocks > 0 && (maxBlocks-1)*5+16 > len(dst) {
		maxBlocks--
	}
	if maxBlocks == 0 {
		return 0, 0
	}
	blocks := decodeBlocksNEON(dst, src, maxBlocks)
	return blocks * 8, blocks * 5
}
