// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·decodeBlocksSSE(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	XORQ AX, AX
	TESTQ CX, CX
	JZ ddone
dloop:
	MOVQ (SI), X0
	MOVO X0, X1
	PSUBB cA<>+0(SB), X1
	PSUBUSB c25<>+0(SB), X1
	PXOR X4, X4
	PCMPEQB X4, X1
	MOVO X0, X2
	PSUBB c2<>+0(SB), X2
	PSUBUSB c5<>+0(SB), X2
	PXOR X5, X5
	PCMPEQB X5, X2
	MOVO X1, X3
	POR X2, X3
	PMOVMSKB X3, DX
	ANDQ $0xff, DX
	CMPQ DX, $0xff
	JNE ddone
	MOVO X0, X6
	PSUBB c65<>+0(SB), X6
	PAND X1, X6
	PSUBB c24<>+0(SB), X0
	PAND X2, X0
	POR X6, X0
	PSHUFB spread<>+0(SB), X0
	PMULLW mul<>+0(SB), X0
	MOVO X0, X7
	PSHUFB g0<>+0(SB), X7
	MOVO X0, X8
	PSHUFB g1<>+0(SB), X8
	POR X8, X7
	PSHUFB g2<>+0(SB), X0
	POR X0, X7
	MOVD X7, (DI)
	PEXTRB $4, X7, 4(DI)
	ADDQ $8, SI
	ADDQ $5, DI
	INCQ AX
	DECQ CX
	JNZ dloop
ddone:
	MOVQ AX, ret+56(FP)
	RET

TEXT ·decodeBlocksAVX2(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	XORQ AX, AX
	VMOVDQU cAb<>+0(SB), Y10
	VMOVDQU c25b<>+0(SB), Y11
	VMOVDQU c2b<>+0(SB), Y12
	VMOVDQU c5b<>+0(SB), Y13
	VMOVDQU c65b<>+0(SB), Y14
	VMOVDQU c24b<>+0(SB), Y15
vloop:
	CMPQ CX, $2
	JLT vtail
	VMOVQ (SI), X0
	VMOVQ 8(SI), X1
	VINSERTI128 $1, X1, Y0, Y0
	VPSUBB Y10, Y0, Y1
	VPSUBUSB Y11, Y1, Y1
	VPXOR Y4, Y4, Y4
	VPCMPEQB Y4, Y1, Y1
	VPSUBB Y12, Y0, Y2
	VPSUBUSB Y13, Y2, Y2
	VPXOR Y5, Y5, Y5
	VPCMPEQB Y5, Y2, Y2
	VPOR Y2, Y1, Y3
	VPMOVMSKB Y3, DX
	MOVQ DX, BX
	ANDQ $0xff, BX
	CMPQ BX, $0xff
	JNE vtail
	MOVQ DX, BX
	SHRQ $16, BX
	ANDQ $0xff, BX
	CMPQ BX, $0xff
	JNE vtail
	VPSUBB Y14, Y0, Y6
	VPAND Y1, Y6, Y6
	VPSUBB Y15, Y0, Y0
	VPAND Y2, Y0, Y0
	VPOR Y6, Y0, Y0
	VPSHUFB spreadb<>+0(SB), Y0, Y0
	VPMULLW mulb<>+0(SB), Y0, Y0
	VPSHUFB g0bb<>+0(SB), Y0, Y7
	VPSHUFB g1bb<>+0(SB), Y0, Y8
	VPOR Y8, Y7, Y7
	VPSHUFB g2bb<>+0(SB), Y0, Y9
	VPOR Y9, Y7, Y7
	VEXTRACTI128 $1, Y7, X8
	VMOVD X7, (DI)
	VPEXTRB $4, X7, 4(DI)
	VMOVD X8, 5(DI)
	VPEXTRB $4, X8, 9(DI)
	ADDQ $16, SI
	ADDQ $10, DI
	ADDQ $2, AX
	SUBQ $2, CX
	JMP vloop
vtail:
	TESTQ CX, CX
	JZ vdone
	VMOVQ (SI), X0
	VPSUBB X10, X0, X1
	VPSUBUSB X11, X1, X1
	VPXOR X4, X4, X4
	VPCMPEQB X4, X1, X1
	VPSUBB X12, X0, X2
	VPSUBUSB X13, X2, X2
	VPXOR X5, X5, X5
	VPCMPEQB X5, X2, X2
	VPOR X2, X1, X3
	VPMOVMSKB X3, DX
	ANDQ $0xff, DX
	CMPQ DX, $0xff
	JNE vdone
	VPSUBB X14, X0, X6
	VPAND X1, X6, X6
	VPSUBB X15, X0, X0
	VPAND X2, X0, X0
	VPOR X6, X0, X0
	VPSHUFB spread<>+0(SB), X0, X0
	VPMULLW mul<>+0(SB), X0, X0
	VPSHUFB g0<>+0(SB), X0, X7
	VPSHUFB g1<>+0(SB), X0, X8
	VPOR X8, X7, X7
	VPSHUFB g2<>+0(SB), X0, X0
	VPOR X0, X7, X7
	VMOVD X7, (DI)
	VPEXTRB $4, X7, 4(DI)
	ADDQ $8, SI
	ADDQ $5, DI
	INCQ AX
vdone:
	VZEROUPPER
	MOVQ AX, ret+56(FP)
	RET

DATA cA<>+0(SB)/1, $0x41
DATA cA<>+1(SB)/1, $0x41
DATA cA<>+2(SB)/1, $0x41
DATA cA<>+3(SB)/1, $0x41
DATA cA<>+4(SB)/1, $0x41
DATA cA<>+5(SB)/1, $0x41
DATA cA<>+6(SB)/1, $0x41
DATA cA<>+7(SB)/1, $0x41
DATA cA<>+8(SB)/1, $0x41
DATA cA<>+9(SB)/1, $0x41
DATA cA<>+10(SB)/1, $0x41
DATA cA<>+11(SB)/1, $0x41
DATA cA<>+12(SB)/1, $0x41
DATA cA<>+13(SB)/1, $0x41
DATA cA<>+14(SB)/1, $0x41
DATA cA<>+15(SB)/1, $0x41
GLOBL cA<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA c2<>+0(SB)/1, $0x32
DATA c2<>+1(SB)/1, $0x32
DATA c2<>+2(SB)/1, $0x32
DATA c2<>+3(SB)/1, $0x32
DATA c2<>+4(SB)/1, $0x32
DATA c2<>+5(SB)/1, $0x32
DATA c2<>+6(SB)/1, $0x32
DATA c2<>+7(SB)/1, $0x32
DATA c2<>+8(SB)/1, $0x32
DATA c2<>+9(SB)/1, $0x32
DATA c2<>+10(SB)/1, $0x32
DATA c2<>+11(SB)/1, $0x32
DATA c2<>+12(SB)/1, $0x32
DATA c2<>+13(SB)/1, $0x32
DATA c2<>+14(SB)/1, $0x32
DATA c2<>+15(SB)/1, $0x32
GLOBL c2<>(SB), RODATA|NOPTR, $16

DATA c5<>+0(SB)/1, $0x05
DATA c5<>+1(SB)/1, $0x05
DATA c5<>+2(SB)/1, $0x05
DATA c5<>+3(SB)/1, $0x05
DATA c5<>+4(SB)/1, $0x05
DATA c5<>+5(SB)/1, $0x05
DATA c5<>+6(SB)/1, $0x05
DATA c5<>+7(SB)/1, $0x05
DATA c5<>+8(SB)/1, $0x05
DATA c5<>+9(SB)/1, $0x05
DATA c5<>+10(SB)/1, $0x05
DATA c5<>+11(SB)/1, $0x05
DATA c5<>+12(SB)/1, $0x05
DATA c5<>+13(SB)/1, $0x05
DATA c5<>+14(SB)/1, $0x05
DATA c5<>+15(SB)/1, $0x05
GLOBL c5<>(SB), RODATA|NOPTR, $16

DATA c65<>+0(SB)/1, $0x41
DATA c65<>+1(SB)/1, $0x41
DATA c65<>+2(SB)/1, $0x41
DATA c65<>+3(SB)/1, $0x41
DATA c65<>+4(SB)/1, $0x41
DATA c65<>+5(SB)/1, $0x41
DATA c65<>+6(SB)/1, $0x41
DATA c65<>+7(SB)/1, $0x41
DATA c65<>+8(SB)/1, $0x41
DATA c65<>+9(SB)/1, $0x41
DATA c65<>+10(SB)/1, $0x41
DATA c65<>+11(SB)/1, $0x41
DATA c65<>+12(SB)/1, $0x41
DATA c65<>+13(SB)/1, $0x41
DATA c65<>+14(SB)/1, $0x41
DATA c65<>+15(SB)/1, $0x41
GLOBL c65<>(SB), RODATA|NOPTR, $16

DATA c24<>+0(SB)/1, $0x18
DATA c24<>+1(SB)/1, $0x18
DATA c24<>+2(SB)/1, $0x18
DATA c24<>+3(SB)/1, $0x18
DATA c24<>+4(SB)/1, $0x18
DATA c24<>+5(SB)/1, $0x18
DATA c24<>+6(SB)/1, $0x18
DATA c24<>+7(SB)/1, $0x18
DATA c24<>+8(SB)/1, $0x18
DATA c24<>+9(SB)/1, $0x18
DATA c24<>+10(SB)/1, $0x18
DATA c24<>+11(SB)/1, $0x18
DATA c24<>+12(SB)/1, $0x18
DATA c24<>+13(SB)/1, $0x18
DATA c24<>+14(SB)/1, $0x18
DATA c24<>+15(SB)/1, $0x18
GLOBL c24<>(SB), RODATA|NOPTR, $16

DATA spread<>+0(SB)/1, $0x00
DATA spread<>+1(SB)/1, $0x80
DATA spread<>+2(SB)/1, $0x01
DATA spread<>+3(SB)/1, $0x80
DATA spread<>+4(SB)/1, $0x02
DATA spread<>+5(SB)/1, $0x80
DATA spread<>+6(SB)/1, $0x03
DATA spread<>+7(SB)/1, $0x80
DATA spread<>+8(SB)/1, $0x04
DATA spread<>+9(SB)/1, $0x80
DATA spread<>+10(SB)/1, $0x05
DATA spread<>+11(SB)/1, $0x80
DATA spread<>+12(SB)/1, $0x06
DATA spread<>+13(SB)/1, $0x80
DATA spread<>+14(SB)/1, $0x07
DATA spread<>+15(SB)/1, $0x80
GLOBL spread<>(SB), RODATA|NOPTR, $16

DATA mul<>+0(SB)/1, $0x00
DATA mul<>+1(SB)/1, $0x08
DATA mul<>+2(SB)/1, $0x40
DATA mul<>+3(SB)/1, $0x00
DATA mul<>+4(SB)/1, $0x00
DATA mul<>+5(SB)/1, $0x02
DATA mul<>+6(SB)/1, $0x10
DATA mul<>+7(SB)/1, $0x00
DATA mul<>+8(SB)/1, $0x80
DATA mul<>+9(SB)/1, $0x00
DATA mul<>+10(SB)/1, $0x00
DATA mul<>+11(SB)/1, $0x04
DATA mul<>+12(SB)/1, $0x20
DATA mul<>+13(SB)/1, $0x00
DATA mul<>+14(SB)/1, $0x00
DATA mul<>+15(SB)/1, $0x01
GLOBL mul<>(SB), RODATA|NOPTR, $16

DATA g0<>+0(SB)/1, $0x01
DATA g0<>+1(SB)/1, $0x02
DATA g0<>+2(SB)/1, $0x06
DATA g0<>+3(SB)/1, $0x08
DATA g0<>+4(SB)/1, $0x0c
DATA g0<>+5(SB)/1, $0x80
DATA g0<>+6(SB)/1, $0x80
DATA g0<>+7(SB)/1, $0x80
DATA g0<>+8(SB)/1, $0x80
DATA g0<>+9(SB)/1, $0x80
DATA g0<>+10(SB)/1, $0x80
DATA g0<>+11(SB)/1, $0x80
DATA g0<>+12(SB)/1, $0x80
DATA g0<>+13(SB)/1, $0x80
DATA g0<>+14(SB)/1, $0x80
DATA g0<>+15(SB)/1, $0x80
GLOBL g0<>(SB), RODATA|NOPTR, $16

DATA g1<>+0(SB)/1, $0x03
DATA g1<>+1(SB)/1, $0x05
DATA g1<>+2(SB)/1, $0x09
DATA g1<>+3(SB)/1, $0x0b
DATA g1<>+4(SB)/1, $0x0f
DATA g1<>+5(SB)/1, $0x80
DATA g1<>+6(SB)/1, $0x80
DATA g1<>+7(SB)/1, $0x80
DATA g1<>+8(SB)/1, $0x80
DATA g1<>+9(SB)/1, $0x80
DATA g1<>+10(SB)/1, $0x80
DATA g1<>+11(SB)/1, $0x80
DATA g1<>+12(SB)/1, $0x80
DATA g1<>+13(SB)/1, $0x80
DATA g1<>+14(SB)/1, $0x80
DATA g1<>+15(SB)/1, $0x80
GLOBL g1<>(SB), RODATA|NOPTR, $16

DATA g2<>+0(SB)/1, $0x80
DATA g2<>+1(SB)/1, $0x07
DATA g2<>+2(SB)/1, $0x80
DATA g2<>+3(SB)/1, $0x0d
DATA g2<>+4(SB)/1, $0x80
DATA g2<>+5(SB)/1, $0x80
DATA g2<>+6(SB)/1, $0x80
DATA g2<>+7(SB)/1, $0x80
DATA g2<>+8(SB)/1, $0x80
DATA g2<>+9(SB)/1, $0x80
DATA g2<>+10(SB)/1, $0x80
DATA g2<>+11(SB)/1, $0x80
DATA g2<>+12(SB)/1, $0x80
DATA g2<>+13(SB)/1, $0x80
DATA g2<>+14(SB)/1, $0x80
DATA g2<>+15(SB)/1, $0x80
GLOBL g2<>(SB), RODATA|NOPTR, $16

DATA cAb<>+0(SB)/1, $0x41
DATA cAb<>+1(SB)/1, $0x41
DATA cAb<>+2(SB)/1, $0x41
DATA cAb<>+3(SB)/1, $0x41
DATA cAb<>+4(SB)/1, $0x41
DATA cAb<>+5(SB)/1, $0x41
DATA cAb<>+6(SB)/1, $0x41
DATA cAb<>+7(SB)/1, $0x41
DATA cAb<>+8(SB)/1, $0x41
DATA cAb<>+9(SB)/1, $0x41
DATA cAb<>+10(SB)/1, $0x41
DATA cAb<>+11(SB)/1, $0x41
DATA cAb<>+12(SB)/1, $0x41
DATA cAb<>+13(SB)/1, $0x41
DATA cAb<>+14(SB)/1, $0x41
DATA cAb<>+15(SB)/1, $0x41
DATA cAb<>+16(SB)/1, $0x41
DATA cAb<>+17(SB)/1, $0x41
DATA cAb<>+18(SB)/1, $0x41
DATA cAb<>+19(SB)/1, $0x41
DATA cAb<>+20(SB)/1, $0x41
DATA cAb<>+21(SB)/1, $0x41
DATA cAb<>+22(SB)/1, $0x41
DATA cAb<>+23(SB)/1, $0x41
DATA cAb<>+24(SB)/1, $0x41
DATA cAb<>+25(SB)/1, $0x41
DATA cAb<>+26(SB)/1, $0x41
DATA cAb<>+27(SB)/1, $0x41
DATA cAb<>+28(SB)/1, $0x41
DATA cAb<>+29(SB)/1, $0x41
DATA cAb<>+30(SB)/1, $0x41
DATA cAb<>+31(SB)/1, $0x41
GLOBL cAb<>(SB), RODATA|NOPTR, $32

DATA c25b<>+0(SB)/1, $0x19
DATA c25b<>+1(SB)/1, $0x19
DATA c25b<>+2(SB)/1, $0x19
DATA c25b<>+3(SB)/1, $0x19
DATA c25b<>+4(SB)/1, $0x19
DATA c25b<>+5(SB)/1, $0x19
DATA c25b<>+6(SB)/1, $0x19
DATA c25b<>+7(SB)/1, $0x19
DATA c25b<>+8(SB)/1, $0x19
DATA c25b<>+9(SB)/1, $0x19
DATA c25b<>+10(SB)/1, $0x19
DATA c25b<>+11(SB)/1, $0x19
DATA c25b<>+12(SB)/1, $0x19
DATA c25b<>+13(SB)/1, $0x19
DATA c25b<>+14(SB)/1, $0x19
DATA c25b<>+15(SB)/1, $0x19
DATA c25b<>+16(SB)/1, $0x19
DATA c25b<>+17(SB)/1, $0x19
DATA c25b<>+18(SB)/1, $0x19
DATA c25b<>+19(SB)/1, $0x19
DATA c25b<>+20(SB)/1, $0x19
DATA c25b<>+21(SB)/1, $0x19
DATA c25b<>+22(SB)/1, $0x19
DATA c25b<>+23(SB)/1, $0x19
DATA c25b<>+24(SB)/1, $0x19
DATA c25b<>+25(SB)/1, $0x19
DATA c25b<>+26(SB)/1, $0x19
DATA c25b<>+27(SB)/1, $0x19
DATA c25b<>+28(SB)/1, $0x19
DATA c25b<>+29(SB)/1, $0x19
DATA c25b<>+30(SB)/1, $0x19
DATA c25b<>+31(SB)/1, $0x19
GLOBL c25b<>(SB), RODATA|NOPTR, $32

DATA c2b<>+0(SB)/1, $0x32
DATA c2b<>+1(SB)/1, $0x32
DATA c2b<>+2(SB)/1, $0x32
DATA c2b<>+3(SB)/1, $0x32
DATA c2b<>+4(SB)/1, $0x32
DATA c2b<>+5(SB)/1, $0x32
DATA c2b<>+6(SB)/1, $0x32
DATA c2b<>+7(SB)/1, $0x32
DATA c2b<>+8(SB)/1, $0x32
DATA c2b<>+9(SB)/1, $0x32
DATA c2b<>+10(SB)/1, $0x32
DATA c2b<>+11(SB)/1, $0x32
DATA c2b<>+12(SB)/1, $0x32
DATA c2b<>+13(SB)/1, $0x32
DATA c2b<>+14(SB)/1, $0x32
DATA c2b<>+15(SB)/1, $0x32
DATA c2b<>+16(SB)/1, $0x32
DATA c2b<>+17(SB)/1, $0x32
DATA c2b<>+18(SB)/1, $0x32
DATA c2b<>+19(SB)/1, $0x32
DATA c2b<>+20(SB)/1, $0x32
DATA c2b<>+21(SB)/1, $0x32
DATA c2b<>+22(SB)/1, $0x32
DATA c2b<>+23(SB)/1, $0x32
DATA c2b<>+24(SB)/1, $0x32
DATA c2b<>+25(SB)/1, $0x32
DATA c2b<>+26(SB)/1, $0x32
DATA c2b<>+27(SB)/1, $0x32
DATA c2b<>+28(SB)/1, $0x32
DATA c2b<>+29(SB)/1, $0x32
DATA c2b<>+30(SB)/1, $0x32
DATA c2b<>+31(SB)/1, $0x32
GLOBL c2b<>(SB), RODATA|NOPTR, $32

DATA c5b<>+0(SB)/1, $0x05
DATA c5b<>+1(SB)/1, $0x05
DATA c5b<>+2(SB)/1, $0x05
DATA c5b<>+3(SB)/1, $0x05
DATA c5b<>+4(SB)/1, $0x05
DATA c5b<>+5(SB)/1, $0x05
DATA c5b<>+6(SB)/1, $0x05
DATA c5b<>+7(SB)/1, $0x05
DATA c5b<>+8(SB)/1, $0x05
DATA c5b<>+9(SB)/1, $0x05
DATA c5b<>+10(SB)/1, $0x05
DATA c5b<>+11(SB)/1, $0x05
DATA c5b<>+12(SB)/1, $0x05
DATA c5b<>+13(SB)/1, $0x05
DATA c5b<>+14(SB)/1, $0x05
DATA c5b<>+15(SB)/1, $0x05
DATA c5b<>+16(SB)/1, $0x05
DATA c5b<>+17(SB)/1, $0x05
DATA c5b<>+18(SB)/1, $0x05
DATA c5b<>+19(SB)/1, $0x05
DATA c5b<>+20(SB)/1, $0x05
DATA c5b<>+21(SB)/1, $0x05
DATA c5b<>+22(SB)/1, $0x05
DATA c5b<>+23(SB)/1, $0x05
DATA c5b<>+24(SB)/1, $0x05
DATA c5b<>+25(SB)/1, $0x05
DATA c5b<>+26(SB)/1, $0x05
DATA c5b<>+27(SB)/1, $0x05
DATA c5b<>+28(SB)/1, $0x05
DATA c5b<>+29(SB)/1, $0x05
DATA c5b<>+30(SB)/1, $0x05
DATA c5b<>+31(SB)/1, $0x05
GLOBL c5b<>(SB), RODATA|NOPTR, $32

DATA c65b<>+0(SB)/1, $0x41
DATA c65b<>+1(SB)/1, $0x41
DATA c65b<>+2(SB)/1, $0x41
DATA c65b<>+3(SB)/1, $0x41
DATA c65b<>+4(SB)/1, $0x41
DATA c65b<>+5(SB)/1, $0x41
DATA c65b<>+6(SB)/1, $0x41
DATA c65b<>+7(SB)/1, $0x41
DATA c65b<>+8(SB)/1, $0x41
DATA c65b<>+9(SB)/1, $0x41
DATA c65b<>+10(SB)/1, $0x41
DATA c65b<>+11(SB)/1, $0x41
DATA c65b<>+12(SB)/1, $0x41
DATA c65b<>+13(SB)/1, $0x41
DATA c65b<>+14(SB)/1, $0x41
DATA c65b<>+15(SB)/1, $0x41
DATA c65b<>+16(SB)/1, $0x41
DATA c65b<>+17(SB)/1, $0x41
DATA c65b<>+18(SB)/1, $0x41
DATA c65b<>+19(SB)/1, $0x41
DATA c65b<>+20(SB)/1, $0x41
DATA c65b<>+21(SB)/1, $0x41
DATA c65b<>+22(SB)/1, $0x41
DATA c65b<>+23(SB)/1, $0x41
DATA c65b<>+24(SB)/1, $0x41
DATA c65b<>+25(SB)/1, $0x41
DATA c65b<>+26(SB)/1, $0x41
DATA c65b<>+27(SB)/1, $0x41
DATA c65b<>+28(SB)/1, $0x41
DATA c65b<>+29(SB)/1, $0x41
DATA c65b<>+30(SB)/1, $0x41
DATA c65b<>+31(SB)/1, $0x41
GLOBL c65b<>(SB), RODATA|NOPTR, $32

DATA c24b<>+0(SB)/1, $0x18
DATA c24b<>+1(SB)/1, $0x18
DATA c24b<>+2(SB)/1, $0x18
DATA c24b<>+3(SB)/1, $0x18
DATA c24b<>+4(SB)/1, $0x18
DATA c24b<>+5(SB)/1, $0x18
DATA c24b<>+6(SB)/1, $0x18
DATA c24b<>+7(SB)/1, $0x18
DATA c24b<>+8(SB)/1, $0x18
DATA c24b<>+9(SB)/1, $0x18
DATA c24b<>+10(SB)/1, $0x18
DATA c24b<>+11(SB)/1, $0x18
DATA c24b<>+12(SB)/1, $0x18
DATA c24b<>+13(SB)/1, $0x18
DATA c24b<>+14(SB)/1, $0x18
DATA c24b<>+15(SB)/1, $0x18
DATA c24b<>+16(SB)/1, $0x18
DATA c24b<>+17(SB)/1, $0x18
DATA c24b<>+18(SB)/1, $0x18
DATA c24b<>+19(SB)/1, $0x18
DATA c24b<>+20(SB)/1, $0x18
DATA c24b<>+21(SB)/1, $0x18
DATA c24b<>+22(SB)/1, $0x18
DATA c24b<>+23(SB)/1, $0x18
DATA c24b<>+24(SB)/1, $0x18
DATA c24b<>+25(SB)/1, $0x18
DATA c24b<>+26(SB)/1, $0x18
DATA c24b<>+27(SB)/1, $0x18
DATA c24b<>+28(SB)/1, $0x18
DATA c24b<>+29(SB)/1, $0x18
DATA c24b<>+30(SB)/1, $0x18
DATA c24b<>+31(SB)/1, $0x18
GLOBL c24b<>(SB), RODATA|NOPTR, $32

DATA spreadb<>+0(SB)/1, $0x00
DATA spreadb<>+1(SB)/1, $0x80
DATA spreadb<>+2(SB)/1, $0x01
DATA spreadb<>+3(SB)/1, $0x80
DATA spreadb<>+4(SB)/1, $0x02
DATA spreadb<>+5(SB)/1, $0x80
DATA spreadb<>+6(SB)/1, $0x03
DATA spreadb<>+7(SB)/1, $0x80
DATA spreadb<>+8(SB)/1, $0x04
DATA spreadb<>+9(SB)/1, $0x80
DATA spreadb<>+10(SB)/1, $0x05
DATA spreadb<>+11(SB)/1, $0x80
DATA spreadb<>+12(SB)/1, $0x06
DATA spreadb<>+13(SB)/1, $0x80
DATA spreadb<>+14(SB)/1, $0x07
DATA spreadb<>+15(SB)/1, $0x80
DATA spreadb<>+16(SB)/1, $0x00
DATA spreadb<>+17(SB)/1, $0x80
DATA spreadb<>+18(SB)/1, $0x01
DATA spreadb<>+19(SB)/1, $0x80
DATA spreadb<>+20(SB)/1, $0x02
DATA spreadb<>+21(SB)/1, $0x80
DATA spreadb<>+22(SB)/1, $0x03
DATA spreadb<>+23(SB)/1, $0x80
DATA spreadb<>+24(SB)/1, $0x04
DATA spreadb<>+25(SB)/1, $0x80
DATA spreadb<>+26(SB)/1, $0x05
DATA spreadb<>+27(SB)/1, $0x80
DATA spreadb<>+28(SB)/1, $0x06
DATA spreadb<>+29(SB)/1, $0x80
DATA spreadb<>+30(SB)/1, $0x07
DATA spreadb<>+31(SB)/1, $0x80
GLOBL spreadb<>(SB), RODATA|NOPTR, $32

DATA mulb<>+0(SB)/1, $0x00
DATA mulb<>+1(SB)/1, $0x08
DATA mulb<>+2(SB)/1, $0x40
DATA mulb<>+3(SB)/1, $0x00
DATA mulb<>+4(SB)/1, $0x00
DATA mulb<>+5(SB)/1, $0x02
DATA mulb<>+6(SB)/1, $0x10
DATA mulb<>+7(SB)/1, $0x00
DATA mulb<>+8(SB)/1, $0x80
DATA mulb<>+9(SB)/1, $0x00
DATA mulb<>+10(SB)/1, $0x00
DATA mulb<>+11(SB)/1, $0x04
DATA mulb<>+12(SB)/1, $0x20
DATA mulb<>+13(SB)/1, $0x00
DATA mulb<>+14(SB)/1, $0x00
DATA mulb<>+15(SB)/1, $0x01
DATA mulb<>+16(SB)/1, $0x00
DATA mulb<>+17(SB)/1, $0x08
DATA mulb<>+18(SB)/1, $0x40
DATA mulb<>+19(SB)/1, $0x00
DATA mulb<>+20(SB)/1, $0x00
DATA mulb<>+21(SB)/1, $0x02
DATA mulb<>+22(SB)/1, $0x10
DATA mulb<>+23(SB)/1, $0x00
DATA mulb<>+24(SB)/1, $0x80
DATA mulb<>+25(SB)/1, $0x00
DATA mulb<>+26(SB)/1, $0x00
DATA mulb<>+27(SB)/1, $0x04
DATA mulb<>+28(SB)/1, $0x20
DATA mulb<>+29(SB)/1, $0x00
DATA mulb<>+30(SB)/1, $0x00
DATA mulb<>+31(SB)/1, $0x01
GLOBL mulb<>(SB), RODATA|NOPTR, $32

DATA g0bb<>+0(SB)/1, $0x01
DATA g0bb<>+1(SB)/1, $0x02
DATA g0bb<>+2(SB)/1, $0x06
DATA g0bb<>+3(SB)/1, $0x08
DATA g0bb<>+4(SB)/1, $0x0c
DATA g0bb<>+5(SB)/1, $0x80
DATA g0bb<>+6(SB)/1, $0x80
DATA g0bb<>+7(SB)/1, $0x80
DATA g0bb<>+8(SB)/1, $0x80
DATA g0bb<>+9(SB)/1, $0x80
DATA g0bb<>+10(SB)/1, $0x80
DATA g0bb<>+11(SB)/1, $0x80
DATA g0bb<>+12(SB)/1, $0x80
DATA g0bb<>+13(SB)/1, $0x80
DATA g0bb<>+14(SB)/1, $0x80
DATA g0bb<>+15(SB)/1, $0x80
DATA g0bb<>+16(SB)/1, $0x01
DATA g0bb<>+17(SB)/1, $0x02
DATA g0bb<>+18(SB)/1, $0x06
DATA g0bb<>+19(SB)/1, $0x08
DATA g0bb<>+20(SB)/1, $0x0c
DATA g0bb<>+21(SB)/1, $0x80
DATA g0bb<>+22(SB)/1, $0x80
DATA g0bb<>+23(SB)/1, $0x80
DATA g0bb<>+24(SB)/1, $0x80
DATA g0bb<>+25(SB)/1, $0x80
DATA g0bb<>+26(SB)/1, $0x80
DATA g0bb<>+27(SB)/1, $0x80
DATA g0bb<>+28(SB)/1, $0x80
DATA g0bb<>+29(SB)/1, $0x80
DATA g0bb<>+30(SB)/1, $0x80
DATA g0bb<>+31(SB)/1, $0x80
GLOBL g0bb<>(SB), RODATA|NOPTR, $32

DATA g1bb<>+0(SB)/1, $0x03
DATA g1bb<>+1(SB)/1, $0x05
DATA g1bb<>+2(SB)/1, $0x09
DATA g1bb<>+3(SB)/1, $0x0b
DATA g1bb<>+4(SB)/1, $0x0f
DATA g1bb<>+5(SB)/1, $0x80
DATA g1bb<>+6(SB)/1, $0x80
DATA g1bb<>+7(SB)/1, $0x80
DATA g1bb<>+8(SB)/1, $0x80
DATA g1bb<>+9(SB)/1, $0x80
DATA g1bb<>+10(SB)/1, $0x80
DATA g1bb<>+11(SB)/1, $0x80
DATA g1bb<>+12(SB)/1, $0x80
DATA g1bb<>+13(SB)/1, $0x80
DATA g1bb<>+14(SB)/1, $0x80
DATA g1bb<>+15(SB)/1, $0x80
DATA g1bb<>+16(SB)/1, $0x03
DATA g1bb<>+17(SB)/1, $0x05
DATA g1bb<>+18(SB)/1, $0x09
DATA g1bb<>+19(SB)/1, $0x0b
DATA g1bb<>+20(SB)/1, $0x0f
DATA g1bb<>+21(SB)/1, $0x80
DATA g1bb<>+22(SB)/1, $0x80
DATA g1bb<>+23(SB)/1, $0x80
DATA g1bb<>+24(SB)/1, $0x80
DATA g1bb<>+25(SB)/1, $0x80
DATA g1bb<>+26(SB)/1, $0x80
DATA g1bb<>+27(SB)/1, $0x80
DATA g1bb<>+28(SB)/1, $0x80
DATA g1bb<>+29(SB)/1, $0x80
DATA g1bb<>+30(SB)/1, $0x80
DATA g1bb<>+31(SB)/1, $0x80
GLOBL g1bb<>(SB), RODATA|NOPTR, $32

DATA g2bb<>+0(SB)/1, $0x80
DATA g2bb<>+1(SB)/1, $0x07
DATA g2bb<>+2(SB)/1, $0x80
DATA g2bb<>+3(SB)/1, $0x0d
DATA g2bb<>+4(SB)/1, $0x80
DATA g2bb<>+5(SB)/1, $0x80
DATA g2bb<>+6(SB)/1, $0x80
DATA g2bb<>+7(SB)/1, $0x80
DATA g2bb<>+8(SB)/1, $0x80
DATA g2bb<>+9(SB)/1, $0x80
DATA g2bb<>+10(SB)/1, $0x80
DATA g2bb<>+11(SB)/1, $0x80
DATA g2bb<>+12(SB)/1, $0x80
DATA g2bb<>+13(SB)/1, $0x80
DATA g2bb<>+14(SB)/1, $0x80
DATA g2bb<>+15(SB)/1, $0x80
DATA g2bb<>+16(SB)/1, $0x80
DATA g2bb<>+17(SB)/1, $0x07
DATA g2bb<>+18(SB)/1, $0x80
DATA g2bb<>+19(SB)/1, $0x0d
DATA g2bb<>+20(SB)/1, $0x80
DATA g2bb<>+21(SB)/1, $0x80
DATA g2bb<>+22(SB)/1, $0x80
DATA g2bb<>+23(SB)/1, $0x80
DATA g2bb<>+24(SB)/1, $0x80
DATA g2bb<>+25(SB)/1, $0x80
DATA g2bb<>+26(SB)/1, $0x80
DATA g2bb<>+27(SB)/1, $0x80
DATA g2bb<>+28(SB)/1, $0x80
DATA g2bb<>+29(SB)/1, $0x80
DATA g2bb<>+30(SB)/1, $0x80
DATA g2bb<>+31(SB)/1, $0x80
GLOBL g2bb<>(SB), RODATA|NOPTR, $32

