// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·decodeBlocksVX(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	MOVD $spread<>(SB), R4
	VL (R4), V8
	MOVD $mul<>(SB), R4
	VL (R4), V9
	MOVD $g0<>(SB), R4
	VL (R4), V10
	MOVD $g1<>(SB), R4
	VL (R4), V11
	MOVD $g2<>(SB), R4
	VL (R4), V12
	MOVD $cA<>(SB), R4
	VL (R4), V13
	MOVD $c25<>(SB), R4
	VL (R4), V14
	MOVD $c2<>(SB), R4
	VL (R4), V15
	MOVD $c5<>(SB), R4
	VL (R4), V16
	MOVD $c65<>(SB), R4
	VL (R4), V17
	MOVD $c24<>(SB), R4
	VL (R4), V18
	VZERO V19
	MOVD $0, R5
	CMPBEQ R3, $0, done
loop:
	VL (R2), V0
	VSB V13, V0, V1
	VCHLB V1, V14, V1
	VNO V1, V1, V1
	VSB V15, V0, V2
	VCHLB V2, V16, V2
	VNO V2, V2, V2
	VO V1, V2, V3
	VLGVG $0, V3, R6
	CMPBNE R6, $-1, done
	VSB V17, V0, V4
	VN V4, V1, V4
	VSB V18, V0, V0
	VN V0, V2, V0
	VO V4, V0, V0
	VPERM V0, V19, V8, V0
	VMLHW V0, V9, V0
	VPERM V0, V19, V10, V5
	VPERM V0, V19, V11, V6
	VO V5, V6, V5
	VPERM V0, V19, V12, V6
	VO V5, V6, V5
	VST V5, (R1)
	ADD $8, R2
	ADD $5, R1
	ADD $1, R5
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	MOVD R5, ret+56(FP)
	RET

DATA spread<>+0(SB)/1, $0x1f
DATA spread<>+1(SB)/1, $0x00
DATA spread<>+2(SB)/1, $0x1f
DATA spread<>+3(SB)/1, $0x01
DATA spread<>+4(SB)/1, $0x1f
DATA spread<>+5(SB)/1, $0x02
DATA spread<>+6(SB)/1, $0x1f
DATA spread<>+7(SB)/1, $0x03
DATA spread<>+8(SB)/1, $0x1f
DATA spread<>+9(SB)/1, $0x04
DATA spread<>+10(SB)/1, $0x1f
DATA spread<>+11(SB)/1, $0x05
DATA spread<>+12(SB)/1, $0x1f
DATA spread<>+13(SB)/1, $0x06
DATA spread<>+14(SB)/1, $0x1f
DATA spread<>+15(SB)/1, $0x07
GLOBL spread<>(SB), RODATA|NOPTR, $16

DATA mul<>+0(SB)/1, $0x08
DATA mul<>+1(SB)/1, $0x00
DATA mul<>+2(SB)/1, $0x00
DATA mul<>+3(SB)/1, $0x40
DATA mul<>+4(SB)/1, $0x02
DATA mul<>+5(SB)/1, $0x00
DATA mul<>+6(SB)/1, $0x00
DATA mul<>+7(SB)/1, $0x10
DATA mul<>+8(SB)/1, $0x00
DATA mul<>+9(SB)/1, $0x80
DATA mul<>+10(SB)/1, $0x04
DATA mul<>+11(SB)/1, $0x00
DATA mul<>+12(SB)/1, $0x00
DATA mul<>+13(SB)/1, $0x20
DATA mul<>+14(SB)/1, $0x01
DATA mul<>+15(SB)/1, $0x00
GLOBL mul<>(SB), RODATA|NOPTR, $16

DATA g0<>+0(SB)/1, $0x00
DATA g0<>+1(SB)/1, $0x03
DATA g0<>+2(SB)/1, $0x07
DATA g0<>+3(SB)/1, $0x09
DATA g0<>+4(SB)/1, $0x0d
DATA g0<>+5(SB)/1, $0x1f
DATA g0<>+6(SB)/1, $0x1f
DATA g0<>+7(SB)/1, $0x1f
DATA g0<>+8(SB)/1, $0x1f
DATA g0<>+9(SB)/1, $0x1f
DATA g0<>+10(SB)/1, $0x1f
DATA g0<>+11(SB)/1, $0x1f
DATA g0<>+12(SB)/1, $0x1f
DATA g0<>+13(SB)/1, $0x1f
DATA g0<>+14(SB)/1, $0x1f
DATA g0<>+15(SB)/1, $0x1f
GLOBL g0<>(SB), RODATA|NOPTR, $16

DATA g1<>+0(SB)/1, $0x02
DATA g1<>+1(SB)/1, $0x04
DATA g1<>+2(SB)/1, $0x08
DATA g1<>+3(SB)/1, $0x0a
DATA g1<>+4(SB)/1, $0x0e
DATA g1<>+5(SB)/1, $0x1f
DATA g1<>+6(SB)/1, $0x1f
DATA g1<>+7(SB)/1, $0x1f
DATA g1<>+8(SB)/1, $0x1f
DATA g1<>+9(SB)/1, $0x1f
DATA g1<>+10(SB)/1, $0x1f
DATA g1<>+11(SB)/1, $0x1f
DATA g1<>+12(SB)/1, $0x1f
DATA g1<>+13(SB)/1, $0x1f
DATA g1<>+14(SB)/1, $0x1f
DATA g1<>+15(SB)/1, $0x1f
GLOBL g1<>(SB), RODATA|NOPTR, $16

DATA g2<>+0(SB)/1, $0x1f
DATA g2<>+1(SB)/1, $0x06
DATA g2<>+2(SB)/1, $0x1f
DATA g2<>+3(SB)/1, $0x0c
DATA g2<>+4(SB)/1, $0x1f
DATA g2<>+5(SB)/1, $0x1f
DATA g2<>+6(SB)/1, $0x1f
DATA g2<>+7(SB)/1, $0x1f
DATA g2<>+8(SB)/1, $0x1f
DATA g2<>+9(SB)/1, $0x1f
DATA g2<>+10(SB)/1, $0x1f
DATA g2<>+11(SB)/1, $0x1f
DATA g2<>+12(SB)/1, $0x1f
DATA g2<>+13(SB)/1, $0x1f
DATA g2<>+14(SB)/1, $0x1f
DATA g2<>+15(SB)/1, $0x1f
GLOBL g2<>(SB), RODATA|NOPTR, $16

DATA cA<>+0(SB)/1, $0x41
DATA cA<>+1(SB)/1, $0x41
DATA cA<>+2(SB)/1, $0x41
DATA cA<>+3(SB)/1, $0x41
DATA cA<>+4(SB)/1, $0x41
DATA cA<>+5(SB)/1, $0x41
DATA cA<>+6(SB)/1, $0x41
DATA cA<>+7(SB)/1, $0x41
DATA cA<>+8(SB)/1, $0x41
DATA cA<>+9(SB)/1, $0x41
DATA cA<>+10(SB)/1, $0x41
DATA cA<>+11(SB)/1, $0x41
DATA cA<>+12(SB)/1, $0x41
DATA cA<>+13(SB)/1, $0x41
DATA cA<>+14(SB)/1, $0x41
DATA cA<>+15(SB)/1, $0x41
GLOBL cA<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA c2<>+0(SB)/1, $0x32
DATA c2<>+1(SB)/1, $0x32
DATA c2<>+2(SB)/1, $0x32
DATA c2<>+3(SB)/1, $0x32
DATA c2<>+4(SB)/1, $0x32
DATA c2<>+5(SB)/1, $0x32
DATA c2<>+6(SB)/1, $0x32
DATA c2<>+7(SB)/1, $0x32
DATA c2<>+8(SB)/1, $0x32
DATA c2<>+9(SB)/1, $0x32
DATA c2<>+10(SB)/1, $0x32
DATA c2<>+11(SB)/1, $0x32
DATA c2<>+12(SB)/1, $0x32
DATA c2<>+13(SB)/1, $0x32
DATA c2<>+14(SB)/1, $0x32
DATA c2<>+15(SB)/1, $0x32
GLOBL c2<>(SB), RODATA|NOPTR, $16

DATA c5<>+0(SB)/1, $0x05
DATA c5<>+1(SB)/1, $0x05
DATA c5<>+2(SB)/1, $0x05
DATA c5<>+3(SB)/1, $0x05
DATA c5<>+4(SB)/1, $0x05
DATA c5<>+5(SB)/1, $0x05
DATA c5<>+6(SB)/1, $0x05
DATA c5<>+7(SB)/1, $0x05
DATA c5<>+8(SB)/1, $0x05
DATA c5<>+9(SB)/1, $0x05
DATA c5<>+10(SB)/1, $0x05
DATA c5<>+11(SB)/1, $0x05
DATA c5<>+12(SB)/1, $0x05
DATA c5<>+13(SB)/1, $0x05
DATA c5<>+14(SB)/1, $0x05
DATA c5<>+15(SB)/1, $0x05
GLOBL c5<>(SB), RODATA|NOPTR, $16

DATA c65<>+0(SB)/1, $0x41
DATA c65<>+1(SB)/1, $0x41
DATA c65<>+2(SB)/1, $0x41
DATA c65<>+3(SB)/1, $0x41
DATA c65<>+4(SB)/1, $0x41
DATA c65<>+5(SB)/1, $0x41
DATA c65<>+6(SB)/1, $0x41
DATA c65<>+7(SB)/1, $0x41
DATA c65<>+8(SB)/1, $0x41
DATA c65<>+9(SB)/1, $0x41
DATA c65<>+10(SB)/1, $0x41
DATA c65<>+11(SB)/1, $0x41
DATA c65<>+12(SB)/1, $0x41
DATA c65<>+13(SB)/1, $0x41
DATA c65<>+14(SB)/1, $0x41
DATA c65<>+15(SB)/1, $0x41
GLOBL c65<>(SB), RODATA|NOPTR, $16

DATA c24<>+0(SB)/1, $0x18
DATA c24<>+1(SB)/1, $0x18
DATA c24<>+2(SB)/1, $0x18
DATA c24<>+3(SB)/1, $0x18
DATA c24<>+4(SB)/1, $0x18
DATA c24<>+5(SB)/1, $0x18
DATA c24<>+6(SB)/1, $0x18
DATA c24<>+7(SB)/1, $0x18
DATA c24<>+8(SB)/1, $0x18
DATA c24<>+9(SB)/1, $0x18
DATA c24<>+10(SB)/1, $0x18
DATA c24<>+11(SB)/1, $0x18
DATA c24<>+12(SB)/1, $0x18
DATA c24<>+13(SB)/1, $0x18
DATA c24<>+14(SB)/1, $0x18
DATA c24<>+15(SB)/1, $0x18
GLOBL c24<>(SB), RODATA|NOPTR, $16

