// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·decodeBlocksNEON(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $c2<>(SB), R3
	VLD1 (R3), [V8.B16]
	MOVD $mask1f<>(SB), R3
	VLD1 (R3), [V9.B16]
	MOVD $spra<>(SB), R3
	VLD1 (R3), [V10.B16]
	MOVD $sprb<>(SB), R3
	VLD1 (R3), [V11.B16]
	MOVD $shl<>(SB), R3
	VLD1 (R3), [V12.B16]
	MOVD $g0<>(SB), R3
	VLD1 (R3), [V13.B16]
	MOVD $g1<>(SB), R3
	VLD1 (R3), [V14.B16]
	MOVD $g2<>(SB), R3
	VLD1 (R3), [V15.B16]
	MOVD $lut0<>(SB), R3
	VLD1 (R3), [V24.B16]
	MOVD $lut1<>(SB), R3
	VLD1 (R3), [V25.B16]
	MOVD $lut2<>(SB), R3
	VLD1 (R3), [V26.B16]
	MOVD $0, R5
pair:
	CMP $2, R2
	BLT single
	VLD1 (R1), [V0.B16]
	VSUB V8.B16, V0.B16, V0.B16
	VTBL V0.B16, [V24.B16, V25.B16, V26.B16], V0.B16
	VUMINV V0.B16, V1
	VMOV V1.B[0], R6
	CMP $0x40, R6
	BLT single
	VAND V9.B16, V0.B16, V0.B16
	VTBL V10.B16, [V0.B16], V20.B16
	VTBL V11.B16, [V0.B16], V21.B16
	VUSHL V12.H8, V20.H8, V20.H8
	VUSHL V12.H8, V21.H8, V21.H8
	VTBL V13.B16, [V20.B16, V21.B16], V2.B16
	VTBL V14.B16, [V20.B16, V21.B16], V3.B16
	VTBL V15.B16, [V20.B16, V21.B16], V4.B16
	VORR V3.B16, V2.B16, V2.B16
	VORR V4.B16, V2.B16, V2.B16
	VST1 [V2.B16], (R0)
	ADD $16, R1
	ADD $10, R0
	ADD $2, R5
	SUB $2, R2
	B pair
single:
	CBZ R2, done
	VLD1 (R1), [V0.B8]
	VSUB V8.B8, V0.B8, V0.B8
	VTBL V0.B8, [V24.B16, V25.B16, V26.B16], V0.B8
	VUMINV V0.B8, V1
	VMOV V1.B[0], R6
	CMP $0x40, R6
	BLT done
	VAND V9.B16, V0.B16, V0.B16
	VTBL V10.B16, [V0.B16], V20.B16
	VUSHL V12.H8, V20.H8, V20.H8
	VTBL V13.B16, [V20.B16], V2.B16
	VTBL V14.B16, [V20.B16], V3.B16
	VTBL V15.B16, [V20.B16], V4.B16
	VORR V3.B16, V2.B16, V2.B16
	VORR V4.B16, V2.B16, V2.B16
	VST1 [V2.B16], (R0)
	ADD $1, R5
done:
	MOVD R5, ret+56(FP)
	RET

DATA c2<>+0(SB)/1, $0x32
DATA c2<>+1(SB)/1, $0x32
DATA c2<>+2(SB)/1, $0x32
DATA c2<>+3(SB)/1, $0x32
DATA c2<>+4(SB)/1, $0x32
DATA c2<>+5(SB)/1, $0x32
DATA c2<>+6(SB)/1, $0x32
DATA c2<>+7(SB)/1, $0x32
DATA c2<>+8(SB)/1, $0x32
DATA c2<>+9(SB)/1, $0x32
DATA c2<>+10(SB)/1, $0x32
DATA c2<>+11(SB)/1, $0x32
DATA c2<>+12(SB)/1, $0x32
DATA c2<>+13(SB)/1, $0x32
DATA c2<>+14(SB)/1, $0x32
DATA c2<>+15(SB)/1, $0x32
GLOBL c2<>(SB), RODATA|NOPTR, $16

DATA lut0<>+0(SB)/1, $0x5a
DATA lut0<>+1(SB)/1, $0x5b
DATA lut0<>+2(SB)/1, $0x5c
DATA lut0<>+3(SB)/1, $0x5d
DATA lut0<>+4(SB)/1, $0x5e
DATA lut0<>+5(SB)/1, $0x5f
DATA lut0<>+6(SB)/1, $0x00
DATA lut0<>+7(SB)/1, $0x00
DATA lut0<>+8(SB)/1, $0x00
DATA lut0<>+9(SB)/1, $0x00
DATA lut0<>+10(SB)/1, $0x00
DATA lut0<>+11(SB)/1, $0x00
DATA lut0<>+12(SB)/1, $0x00
DATA lut0<>+13(SB)/1, $0x00
DATA lut0<>+14(SB)/1, $0x00
DATA lut0<>+15(SB)/1, $0x40
GLOBL lut0<>(SB), RODATA|NOPTR, $16

DATA lut1<>+0(SB)/1, $0x41
DATA lut1<>+1(SB)/1, $0x42
DATA lut1<>+2(SB)/1, $0x43
DATA lut1<>+3(SB)/1, $0x44
DATA lut1<>+4(SB)/1, $0x45
DATA lut1<>+5(SB)/1, $0x46
DATA lut1<>+6(SB)/1, $0x47
DATA lut1<>+7(SB)/1, $0x48
DATA lut1<>+8(SB)/1, $0x49
DATA lut1<>+9(SB)/1, $0x4a
DATA lut1<>+10(SB)/1, $0x4b
DATA lut1<>+11(SB)/1, $0x4c
DATA lut1<>+12(SB)/1, $0x4d
DATA lut1<>+13(SB)/1, $0x4e
DATA lut1<>+14(SB)/1, $0x4f
DATA lut1<>+15(SB)/1, $0x50
GLOBL lut1<>(SB), RODATA|NOPTR, $16

DATA lut2<>+0(SB)/1, $0x51
DATA lut2<>+1(SB)/1, $0x52
DATA lut2<>+2(SB)/1, $0x53
DATA lut2<>+3(SB)/1, $0x54
DATA lut2<>+4(SB)/1, $0x55
DATA lut2<>+5(SB)/1, $0x56
DATA lut2<>+6(SB)/1, $0x57
DATA lut2<>+7(SB)/1, $0x58
DATA lut2<>+8(SB)/1, $0x59
DATA lut2<>+9(SB)/1, $0x00
DATA lut2<>+10(SB)/1, $0x00
DATA lut2<>+11(SB)/1, $0x00
DATA lut2<>+12(SB)/1, $0x00
DATA lut2<>+13(SB)/1, $0x00
DATA lut2<>+14(SB)/1, $0x00
DATA lut2<>+15(SB)/1, $0x00
GLOBL lut2<>(SB), RODATA|NOPTR, $16

DATA mask1f<>+0(SB)/1, $0x1f
DATA mask1f<>+1(SB)/1, $0x1f
DATA mask1f<>+2(SB)/1, $0x1f
DATA mask1f<>+3(SB)/1, $0x1f
DATA mask1f<>+4(SB)/1, $0x1f
DATA mask1f<>+5(SB)/1, $0x1f
DATA mask1f<>+6(SB)/1, $0x1f
DATA mask1f<>+7(SB)/1, $0x1f
DATA mask1f<>+8(SB)/1, $0x1f
DATA mask1f<>+9(SB)/1, $0x1f
DATA mask1f<>+10(SB)/1, $0x1f
DATA mask1f<>+11(SB)/1, $0x1f
DATA mask1f<>+12(SB)/1, $0x1f
DATA mask1f<>+13(SB)/1, $0x1f
DATA mask1f<>+14(SB)/1, $0x1f
DATA mask1f<>+15(SB)/1, $0x1f
GLOBL mask1f<>(SB), RODATA|NOPTR, $16

DATA spra<>+0(SB)/1, $0x00
DATA spra<>+1(SB)/1, $0xff
DATA spra<>+2(SB)/1, $0x01
DATA spra<>+3(SB)/1, $0xff
DATA spra<>+4(SB)/1, $0x02
DATA spra<>+5(SB)/1, $0xff
DATA spra<>+6(SB)/1, $0x03
DATA spra<>+7(SB)/1, $0xff
DATA spra<>+8(SB)/1, $0x04
DATA spra<>+9(SB)/1, $0xff
DATA spra<>+10(SB)/1, $0x05
DATA spra<>+11(SB)/1, $0xff
DATA spra<>+12(SB)/1, $0x06
DATA spra<>+13(SB)/1, $0xff
DATA spra<>+14(SB)/1, $0x07
DATA spra<>+15(SB)/1, $0xff
GLOBL spra<>(SB), RODATA|NOPTR, $16

DATA sprb<>+0(SB)/1, $0x08
DATA sprb<>+1(SB)/1, $0xff
DATA sprb<>+2(SB)/1, $0x09
DATA sprb<>+3(SB)/1, $0xff
DATA sprb<>+4(SB)/1, $0x0a
DATA sprb<>+5(SB)/1, $0xff
DATA sprb<>+6(SB)/1, $0x0b
DATA sprb<>+7(SB)/1, $0xff
DATA sprb<>+8(SB)/1, $0x0c
DATA sprb<>+9(SB)/1, $0xff
DATA sprb<>+10(SB)/1, $0x0d
DATA sprb<>+11(SB)/1, $0xff
DATA sprb<>+12(SB)/1, $0x0e
DATA sprb<>+13(SB)/1, $0xff
DATA sprb<>+14(SB)/1, $0x0f
DATA sprb<>+15(SB)/1, $0xff
GLOBL sprb<>(SB), RODATA|NOPTR, $16

DATA shl<>+0(SB)/1, $0x0b
DATA shl<>+1(SB)/1, $0x00
DATA shl<>+2(SB)/1, $0x06
DATA shl<>+3(SB)/1, $0x00
DATA shl<>+4(SB)/1, $0x09
DATA shl<>+5(SB)/1, $0x00
DATA shl<>+6(SB)/1, $0x04
DATA shl<>+7(SB)/1, $0x00
DATA shl<>+8(SB)/1, $0x07
DATA shl<>+9(SB)/1, $0x00
DATA shl<>+10(SB)/1, $0x0a
DATA shl<>+11(SB)/1, $0x00
DATA shl<>+12(SB)/1, $0x05
DATA shl<>+13(SB)/1, $0x00
DATA shl<>+14(SB)/1, $0x08
DATA shl<>+15(SB)/1, $0x00
GLOBL shl<>(SB), RODATA|NOPTR, $16

DATA g0<>+0(SB)/1, $0x01
DATA g0<>+1(SB)/1, $0x02
DATA g0<>+2(SB)/1, $0x06
DATA g0<>+3(SB)/1, $0x08
DATA g0<>+4(SB)/1, $0x0c
DATA g0<>+5(SB)/1, $0x11
DATA g0<>+6(SB)/1, $0x12
DATA g0<>+7(SB)/1, $0x16
DATA g0<>+8(SB)/1, $0x18
DATA g0<>+9(SB)/1, $0x1c
DATA g0<>+10(SB)/1, $0xff
DATA g0<>+11(SB)/1, $0xff
DATA g0<>+12(SB)/1, $0xff
DATA g0<>+13(SB)/1, $0xff
DATA g0<>+14(SB)/1, $0xff
DATA g0<>+15(SB)/1, $0xff
GLOBL g0<>(SB), RODATA|NOPTR, $16

DATA g1<>+0(SB)/1, $0x03
DATA g1<>+1(SB)/1, $0x05
DATA g1<>+2(SB)/1, $0x09
DATA g1<>+3(SB)/1, $0x0b
DATA g1<>+4(SB)/1, $0x0f
DATA g1<>+5(SB)/1, $0x13
DATA g1<>+6(SB)/1, $0x15
DATA g1<>+7(SB)/1, $0x19
DATA g1<>+8(SB)/1, $0x1b
DATA g1<>+9(SB)/1, $0x1f
DATA g1<>+10(SB)/1, $0xff
DATA g1<>+11(SB)/1, $0xff
DATA g1<>+12(SB)/1, $0xff
DATA g1<>+13(SB)/1, $0xff
DATA g1<>+14(SB)/1, $0xff
DATA g1<>+15(SB)/1, $0xff
GLOBL g1<>(SB), RODATA|NOPTR, $16

DATA g2<>+0(SB)/1, $0xff
DATA g2<>+1(SB)/1, $0x07
DATA g2<>+2(SB)/1, $0xff
DATA g2<>+3(SB)/1, $0x0d
DATA g2<>+4(SB)/1, $0xff
DATA g2<>+5(SB)/1, $0xff
DATA g2<>+6(SB)/1, $0x17
DATA g2<>+7(SB)/1, $0xff
DATA g2<>+8(SB)/1, $0x1d
DATA g2<>+9(SB)/1, $0xff
DATA g2<>+10(SB)/1, $0xff
DATA g2<>+11(SB)/1, $0xff
DATA g2<>+12(SB)/1, $0xff
DATA g2<>+13(SB)/1, $0xff
DATA g2<>+14(SB)/1, $0xff
DATA g2<>+15(SB)/1, $0xff
GLOBL g2<>(SB), RODATA|NOPTR, $16

