//go:build amd64

package base32

// decodeBlocksSSE (8 chars -> 5 bytes) and decodeBlocksAVX2 (two blocks at a
// time, one per 128-bit lane) are the vectorised base32 decoders generated by
// go-asmgen (decode_gen.go), in decode_amd64.s. Each returns the number of
// 8-char blocks it actually decoded; it stops before the first block that
// contains a non-alphabet char so the caller can hand the remainder (errors,
// padding) to encoding/base32.
func decodeBlocksSSE(dst, src []byte, n int) int
func decodeBlocksAVX2(dst, src []byte, n int) int

// decodeSIMD decodes whole 8-char blocks of valid alphabet chars from the front
// of src, leaving the final block (and anything after the first invalid char) to
// encoding/base32 so padding/tail/error semantics stay byte-and-error identical.
// It returns the number of src bytes consumed and dst bytes written.
func decodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	full := len(src) / 8
	if full < 2 {
		return 0, 0 // need at least one block to run + one reserved for stdlib
	}
	maxBlocks := full - 1 // always reserve the final block for the stdlib tail
	var blocks int
	// AVX2 stores 10 bytes per pair of blocks and SSE/AVX2 both PEXTRB-store the
	// 5th byte one block at a time, so no over-store slack is needed beyond the
	// reserved final block (dst always has room for maxBlocks*5 here).
	if hasAVX2 {
		blocks = decodeBlocksAVX2(dst, src, maxBlocks)
	} else {
		blocks = decodeBlocksSSE(dst, src, maxBlocks)
	}
	return blocks * 8, blocks * 5
}
