//go:build s390x

package base32

// encodeBlocksVX (5 bytes -> 8 chars per iteration) is the vectorised base32
// encoder for the z13+ vector facility. Generated by go-asmgen
// (encode_s390x_gen.go), in encode_s390x.s. s390x is big-endian; see the
// generator for the cross-lane (VPERM) layout. The vector facility is baseline
// on z13+, so there is no runtime dispatch.
func encodeBlocksVX(dst, src []byte, n int)

// encodeSIMD runs the vector kernel over the part of src where both its 16-byte
// over-reading load and its 16-byte store stay in bounds, reporting bytes
// consumed/written so the caller finishes the tail with encoding/base32. Each
// 5-byte group emits 8 chars but the store writes a full 16-byte vector, so the
// final group must keep 8 bytes of slack in dst.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/5 + 1
	// Cap so the last 16-byte VST (starting at dst[(groups-1)*8]) stays in bounds.
	for groups > 0 && (groups-1)*8+16 > len(dst) {
		groups--
	}
	if groups == 0 {
		return 0, 0
	}
	encodeBlocksVX(dst, src, groups)
	return groups * 5, groups * 8
}
