// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·encodeBlocksSSE(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU shuf<>+0(SB), X8
	MOVOU mul<>+0(SB), X9
	MOVOU pack<>+0(SB), X10
	MOVOU c25<>+0(SB), X11
	MOVOU c65<>+0(SB), X12
	MOVOU c41<>+0(SB), X13
	TESTQ CX, CX
	JZ sdone
sloop:
	MOVOU (SI), X0
	PSHUFB X8, X0
	PMULHUW X9, X0
	PAND mask1f<>+0(SB), X0
	PSHUFB X10, X0
	MOVO X0, X1
	PCMPGTB X11, X1
	PAND X13, X1
	PADDB X12, X0
	PSUBB X1, X0
	MOVQ X0, (DI)
	ADDQ $5, SI
	ADDQ $8, DI
	DECQ CX
	JNZ sloop
sdone:
	RET

TEXT ·encodeBlocksAVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU shufb<>+0(SB), Y8
	VMOVDQU mulb<>+0(SB), Y9
	VMOVDQU maskb<>+0(SB), Y10
	VMOVDQU packb<>+0(SB), Y11
	VMOVDQU c25b<>+0(SB), Y12
	VMOVDQU c65b<>+0(SB), Y13
	VMOVDQU c41b<>+0(SB), Y14
	TESTQ CX, CX
	JZ vdone
vpair:
	CMPQ CX, $2
	JLT vsingle
	VMOVDQU (SI), X0
	VINSERTI128 $1, 5(SI), Y0, Y0
	VMOVDQU 10(SI), X2
	VINSERTI128 $1, 15(SI), Y2, Y2
	VPSHUFB Y8, Y0, Y0
	VPSHUFB Y8, Y2, Y2
	VPMULHUW Y9, Y0, Y0
	VPMULHUW Y9, Y2, Y2
	VPAND Y10, Y0, Y0
	VPAND Y10, Y2, Y2
	VPSHUFB Y11, Y0, Y0
	VPSHUFB Y11, Y2, Y2
	VPCMPGTB Y12, Y0, Y1
	VPCMPGTB Y12, Y2, Y3
	VPAND Y14, Y1, Y1
	VPAND Y14, Y3, Y3
	VPADDB Y13, Y0, Y0
	VPADDB Y13, Y2, Y2
	VPSUBB Y1, Y0, Y0
	VPSUBB Y3, Y2, Y2
	VPERMQ $0x08, Y0, Y0
	VPERMQ $0x08, Y2, Y2
	VMOVDQU X0, (DI)
	VMOVDQU X2, 16(DI)
	ADDQ $20, SI
	ADDQ $32, DI
	SUBQ $2, CX
	JMP vpair
vsingle:
	TESTQ CX, CX
	JZ vdone
	VMOVDQU (SI), X0
	VINSERTI128 $1, 5(SI), Y0, Y0
	VPSHUFB Y8, Y0, Y0
	VPMULHUW Y9, Y0, Y0
	VPAND Y10, Y0, Y0
	VPSHUFB Y11, Y0, Y0
	VPCMPGTB Y12, Y0, Y1
	VPAND Y14, Y1, Y1
	VPADDB Y13, Y0, Y0
	VPSUBB Y1, Y0, Y0
	VPERMQ $0x08, Y0, Y0
	VMOVDQU X0, (DI)
vdone:
	VZEROUPPER
	RET

DATA shuf<>+0(SB)/1, $0x00
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x01
DATA shuf<>+3(SB)/1, $0x00
DATA shuf<>+4(SB)/1, $0x01
DATA shuf<>+5(SB)/1, $0x01
DATA shuf<>+6(SB)/1, $0x02
DATA shuf<>+7(SB)/1, $0x01
DATA shuf<>+8(SB)/1, $0x03
DATA shuf<>+9(SB)/1, $0x02
DATA shuf<>+10(SB)/1, $0x03
DATA shuf<>+11(SB)/1, $0x03
DATA shuf<>+12(SB)/1, $0x04
DATA shuf<>+13(SB)/1, $0x03
DATA shuf<>+14(SB)/1, $0x04
DATA shuf<>+15(SB)/1, $0x04
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA mul<>+0(SB)/1, $0x20
DATA mul<>+1(SB)/1, $0x00
DATA mul<>+2(SB)/1, $0x00
DATA mul<>+3(SB)/1, $0x04
DATA mul<>+4(SB)/1, $0x80
DATA mul<>+5(SB)/1, $0x00
DATA mul<>+6(SB)/1, $0x00
DATA mul<>+7(SB)/1, $0x10
DATA mul<>+8(SB)/1, $0x00
DATA mul<>+9(SB)/1, $0x02
DATA mul<>+10(SB)/1, $0x40
DATA mul<>+11(SB)/1, $0x00
DATA mul<>+12(SB)/1, $0x00
DATA mul<>+13(SB)/1, $0x08
DATA mul<>+14(SB)/1, $0x00
DATA mul<>+15(SB)/1, $0x01
GLOBL mul<>(SB), RODATA|NOPTR, $16

DATA mask1f<>+0(SB)/1, $0x1f
DATA mask1f<>+1(SB)/1, $0x1f
DATA mask1f<>+2(SB)/1, $0x1f
DATA mask1f<>+3(SB)/1, $0x1f
DATA mask1f<>+4(SB)/1, $0x1f
DATA mask1f<>+5(SB)/1, $0x1f
DATA mask1f<>+6(SB)/1, $0x1f
DATA mask1f<>+7(SB)/1, $0x1f
DATA mask1f<>+8(SB)/1, $0x1f
DATA mask1f<>+9(SB)/1, $0x1f
DATA mask1f<>+10(SB)/1, $0x1f
DATA mask1f<>+11(SB)/1, $0x1f
DATA mask1f<>+12(SB)/1, $0x1f
DATA mask1f<>+13(SB)/1, $0x1f
DATA mask1f<>+14(SB)/1, $0x1f
DATA mask1f<>+15(SB)/1, $0x1f
GLOBL mask1f<>(SB), RODATA|NOPTR, $16

DATA pack<>+0(SB)/1, $0x00
DATA pack<>+1(SB)/1, $0x02
DATA pack<>+2(SB)/1, $0x04
DATA pack<>+3(SB)/1, $0x06
DATA pack<>+4(SB)/1, $0x08
DATA pack<>+5(SB)/1, $0x0a
DATA pack<>+6(SB)/1, $0x0c
DATA pack<>+7(SB)/1, $0x0e
DATA pack<>+8(SB)/1, $0x80
DATA pack<>+9(SB)/1, $0x80
DATA pack<>+10(SB)/1, $0x80
DATA pack<>+11(SB)/1, $0x80
DATA pack<>+12(SB)/1, $0x80
DATA pack<>+13(SB)/1, $0x80
DATA pack<>+14(SB)/1, $0x80
DATA pack<>+15(SB)/1, $0x80
GLOBL pack<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA c65<>+0(SB)/1, $0x41
DATA c65<>+1(SB)/1, $0x41
DATA c65<>+2(SB)/1, $0x41
DATA c65<>+3(SB)/1, $0x41
DATA c65<>+4(SB)/1, $0x41
DATA c65<>+5(SB)/1, $0x41
DATA c65<>+6(SB)/1, $0x41
DATA c65<>+7(SB)/1, $0x41
DATA c65<>+8(SB)/1, $0x41
DATA c65<>+9(SB)/1, $0x41
DATA c65<>+10(SB)/1, $0x41
DATA c65<>+11(SB)/1, $0x41
DATA c65<>+12(SB)/1, $0x41
DATA c65<>+13(SB)/1, $0x41
DATA c65<>+14(SB)/1, $0x41
DATA c65<>+15(SB)/1, $0x41
GLOBL c65<>(SB), RODATA|NOPTR, $16

DATA c41<>+0(SB)/1, $0x29
DATA c41<>+1(SB)/1, $0x29
DATA c41<>+2(SB)/1, $0x29
DATA c41<>+3(SB)/1, $0x29
DATA c41<>+4(SB)/1, $0x29
DATA c41<>+5(SB)/1, $0x29
DATA c41<>+6(SB)/1, $0x29
DATA c41<>+7(SB)/1, $0x29
DATA c41<>+8(SB)/1, $0x29
DATA c41<>+9(SB)/1, $0x29
DATA c41<>+10(SB)/1, $0x29
DATA c41<>+11(SB)/1, $0x29
DATA c41<>+12(SB)/1, $0x29
DATA c41<>+13(SB)/1, $0x29
DATA c41<>+14(SB)/1, $0x29
DATA c41<>+15(SB)/1, $0x29
GLOBL c41<>(SB), RODATA|NOPTR, $16

DATA shufb<>+0(SB)/1, $0x00
DATA shufb<>+1(SB)/1, $0x00
DATA shufb<>+2(SB)/1, $0x01
DATA shufb<>+3(SB)/1, $0x00
DATA shufb<>+4(SB)/1, $0x01
DATA shufb<>+5(SB)/1, $0x01
DATA shufb<>+6(SB)/1, $0x02
DATA shufb<>+7(SB)/1, $0x01
DATA shufb<>+8(SB)/1, $0x03
DATA shufb<>+9(SB)/1, $0x02
DATA shufb<>+10(SB)/1, $0x03
DATA shufb<>+11(SB)/1, $0x03
DATA shufb<>+12(SB)/1, $0x04
DATA shufb<>+13(SB)/1, $0x03
DATA shufb<>+14(SB)/1, $0x04
DATA shufb<>+15(SB)/1, $0x04
DATA shufb<>+16(SB)/1, $0x00
DATA shufb<>+17(SB)/1, $0x00
DATA shufb<>+18(SB)/1, $0x01
DATA shufb<>+19(SB)/1, $0x00
DATA shufb<>+20(SB)/1, $0x01
DATA shufb<>+21(SB)/1, $0x01
DATA shufb<>+22(SB)/1, $0x02
DATA shufb<>+23(SB)/1, $0x01
DATA shufb<>+24(SB)/1, $0x03
DATA shufb<>+25(SB)/1, $0x02
DATA shufb<>+26(SB)/1, $0x03
DATA shufb<>+27(SB)/1, $0x03
DATA shufb<>+28(SB)/1, $0x04
DATA shufb<>+29(SB)/1, $0x03
DATA shufb<>+30(SB)/1, $0x04
DATA shufb<>+31(SB)/1, $0x04
GLOBL shufb<>(SB), RODATA|NOPTR, $32

DATA mulb<>+0(SB)/1, $0x20
DATA mulb<>+1(SB)/1, $0x00
DATA mulb<>+2(SB)/1, $0x00
DATA mulb<>+3(SB)/1, $0x04
DATA mulb<>+4(SB)/1, $0x80
DATA mulb<>+5(SB)/1, $0x00
DATA mulb<>+6(SB)/1, $0x00
DATA mulb<>+7(SB)/1, $0x10
DATA mulb<>+8(SB)/1, $0x00
DATA mulb<>+9(SB)/1, $0x02
DATA mulb<>+10(SB)/1, $0x40
DATA mulb<>+11(SB)/1, $0x00
DATA mulb<>+12(SB)/1, $0x00
DATA mulb<>+13(SB)/1, $0x08
DATA mulb<>+14(SB)/1, $0x00
DATA mulb<>+15(SB)/1, $0x01
DATA mulb<>+16(SB)/1, $0x20
DATA mulb<>+17(SB)/1, $0x00
DATA mulb<>+18(SB)/1, $0x00
DATA mulb<>+19(SB)/1, $0x04
DATA mulb<>+20(SB)/1, $0x80
DATA mulb<>+21(SB)/1, $0x00
DATA mulb<>+22(SB)/1, $0x00
DATA mulb<>+23(SB)/1, $0x10
DATA mulb<>+24(SB)/1, $0x00
DATA mulb<>+25(SB)/1, $0x02
DATA mulb<>+26(SB)/1, $0x40
DATA mulb<>+27(SB)/1, $0x00
DATA mulb<>+28(SB)/1, $0x00
DATA mulb<>+29(SB)/1, $0x08
DATA mulb<>+30(SB)/1, $0x00
DATA mulb<>+31(SB)/1, $0x01
GLOBL mulb<>(SB), RODATA|NOPTR, $32

DATA maskb<>+0(SB)/1, $0x1f
DATA maskb<>+1(SB)/1, $0x1f
DATA maskb<>+2(SB)/1, $0x1f
DATA maskb<>+3(SB)/1, $0x1f
DATA maskb<>+4(SB)/1, $0x1f
DATA maskb<>+5(SB)/1, $0x1f
DATA maskb<>+6(SB)/1, $0x1f
DATA maskb<>+7(SB)/1, $0x1f
DATA maskb<>+8(SB)/1, $0x1f
DATA maskb<>+9(SB)/1, $0x1f
DATA maskb<>+10(SB)/1, $0x1f
DATA maskb<>+11(SB)/1, $0x1f
DATA maskb<>+12(SB)/1, $0x1f
DATA maskb<>+13(SB)/1, $0x1f
DATA maskb<>+14(SB)/1, $0x1f
DATA maskb<>+15(SB)/1, $0x1f
DATA maskb<>+16(SB)/1, $0x1f
DATA maskb<>+17(SB)/1, $0x1f
DATA maskb<>+18(SB)/1, $0x1f
DATA maskb<>+19(SB)/1, $0x1f
DATA maskb<>+20(SB)/1, $0x1f
DATA maskb<>+21(SB)/1, $0x1f
DATA maskb<>+22(SB)/1, $0x1f
DATA maskb<>+23(SB)/1, $0x1f
DATA maskb<>+24(SB)/1, $0x1f
DATA maskb<>+25(SB)/1, $0x1f
DATA maskb<>+26(SB)/1, $0x1f
DATA maskb<>+27(SB)/1, $0x1f
DATA maskb<>+28(SB)/1, $0x1f
DATA maskb<>+29(SB)/1, $0x1f
DATA maskb<>+30(SB)/1, $0x1f
DATA maskb<>+31(SB)/1, $0x1f
GLOBL maskb<>(SB), RODATA|NOPTR, $32

DATA packb<>+0(SB)/1, $0x00
DATA packb<>+1(SB)/1, $0x02
DATA packb<>+2(SB)/1, $0x04
DATA packb<>+3(SB)/1, $0x06
DATA packb<>+4(SB)/1, $0x08
DATA packb<>+5(SB)/1, $0x0a
DATA packb<>+6(SB)/1, $0x0c
DATA packb<>+7(SB)/1, $0x0e
DATA packb<>+8(SB)/1, $0x80
DATA packb<>+9(SB)/1, $0x80
DATA packb<>+10(SB)/1, $0x80
DATA packb<>+11(SB)/1, $0x80
DATA packb<>+12(SB)/1, $0x80
DATA packb<>+13(SB)/1, $0x80
DATA packb<>+14(SB)/1, $0x80
DATA packb<>+15(SB)/1, $0x80
DATA packb<>+16(SB)/1, $0x00
DATA packb<>+17(SB)/1, $0x02
DATA packb<>+18(SB)/1, $0x04
DATA packb<>+19(SB)/1, $0x06
DATA packb<>+20(SB)/1, $0x08
DATA packb<>+21(SB)/1, $0x0a
DATA packb<>+22(SB)/1, $0x0c
DATA packb<>+23(SB)/1, $0x0e
DATA packb<>+24(SB)/1, $0x80
DATA packb<>+25(SB)/1, $0x80
DATA packb<>+26(SB)/1, $0x80
DATA packb<>+27(SB)/1, $0x80
DATA packb<>+28(SB)/1, $0x80
DATA packb<>+29(SB)/1, $0x80
DATA packb<>+30(SB)/1, $0x80
DATA packb<>+31(SB)/1, $0x80
GLOBL packb<>(SB), RODATA|NOPTR, $32

DATA c25b<>+0(SB)/1, $0x19
DATA c25b<>+1(SB)/1, $0x19
DATA c25b<>+2(SB)/1, $0x19
DATA c25b<>+3(SB)/1, $0x19
DATA c25b<>+4(SB)/1, $0x19
DATA c25b<>+5(SB)/1, $0x19
DATA c25b<>+6(SB)/1, $0x19
DATA c25b<>+7(SB)/1, $0x19
DATA c25b<>+8(SB)/1, $0x19
DATA c25b<>+9(SB)/1, $0x19
DATA c25b<>+10(SB)/1, $0x19
DATA c25b<>+11(SB)/1, $0x19
DATA c25b<>+12(SB)/1, $0x19
DATA c25b<>+13(SB)/1, $0x19
DATA c25b<>+14(SB)/1, $0x19
DATA c25b<>+15(SB)/1, $0x19
DATA c25b<>+16(SB)/1, $0x19
DATA c25b<>+17(SB)/1, $0x19
DATA c25b<>+18(SB)/1, $0x19
DATA c25b<>+19(SB)/1, $0x19
DATA c25b<>+20(SB)/1, $0x19
DATA c25b<>+21(SB)/1, $0x19
DATA c25b<>+22(SB)/1, $0x19
DATA c25b<>+23(SB)/1, $0x19
DATA c25b<>+24(SB)/1, $0x19
DATA c25b<>+25(SB)/1, $0x19
DATA c25b<>+26(SB)/1, $0x19
DATA c25b<>+27(SB)/1, $0x19
DATA c25b<>+28(SB)/1, $0x19
DATA c25b<>+29(SB)/1, $0x19
DATA c25b<>+30(SB)/1, $0x19
DATA c25b<>+31(SB)/1, $0x19
GLOBL c25b<>(SB), RODATA|NOPTR, $32

DATA c65b<>+0(SB)/1, $0x41
DATA c65b<>+1(SB)/1, $0x41
DATA c65b<>+2(SB)/1, $0x41
DATA c65b<>+3(SB)/1, $0x41
DATA c65b<>+4(SB)/1, $0x41
DATA c65b<>+5(SB)/1, $0x41
DATA c65b<>+6(SB)/1, $0x41
DATA c65b<>+7(SB)/1, $0x41
DATA c65b<>+8(SB)/1, $0x41
DATA c65b<>+9(SB)/1, $0x41
DATA c65b<>+10(SB)/1, $0x41
DATA c65b<>+11(SB)/1, $0x41
DATA c65b<>+12(SB)/1, $0x41
DATA c65b<>+13(SB)/1, $0x41
DATA c65b<>+14(SB)/1, $0x41
DATA c65b<>+15(SB)/1, $0x41
DATA c65b<>+16(SB)/1, $0x41
DATA c65b<>+17(SB)/1, $0x41
DATA c65b<>+18(SB)/1, $0x41
DATA c65b<>+19(SB)/1, $0x41
DATA c65b<>+20(SB)/1, $0x41
DATA c65b<>+21(SB)/1, $0x41
DATA c65b<>+22(SB)/1, $0x41
DATA c65b<>+23(SB)/1, $0x41
DATA c65b<>+24(SB)/1, $0x41
DATA c65b<>+25(SB)/1, $0x41
DATA c65b<>+26(SB)/1, $0x41
DATA c65b<>+27(SB)/1, $0x41
DATA c65b<>+28(SB)/1, $0x41
DATA c65b<>+29(SB)/1, $0x41
DATA c65b<>+30(SB)/1, $0x41
DATA c65b<>+31(SB)/1, $0x41
GLOBL c65b<>(SB), RODATA|NOPTR, $32

DATA c41b<>+0(SB)/1, $0x29
DATA c41b<>+1(SB)/1, $0x29
DATA c41b<>+2(SB)/1, $0x29
DATA c41b<>+3(SB)/1, $0x29
DATA c41b<>+4(SB)/1, $0x29
DATA c41b<>+5(SB)/1, $0x29
DATA c41b<>+6(SB)/1, $0x29
DATA c41b<>+7(SB)/1, $0x29
DATA c41b<>+8(SB)/1, $0x29
DATA c41b<>+9(SB)/1, $0x29
DATA c41b<>+10(SB)/1, $0x29
DATA c41b<>+11(SB)/1, $0x29
DATA c41b<>+12(SB)/1, $0x29
DATA c41b<>+13(SB)/1, $0x29
DATA c41b<>+14(SB)/1, $0x29
DATA c41b<>+15(SB)/1, $0x29
DATA c41b<>+16(SB)/1, $0x29
DATA c41b<>+17(SB)/1, $0x29
DATA c41b<>+18(SB)/1, $0x29
DATA c41b<>+19(SB)/1, $0x29
DATA c41b<>+20(SB)/1, $0x29
DATA c41b<>+21(SB)/1, $0x29
DATA c41b<>+22(SB)/1, $0x29
DATA c41b<>+23(SB)/1, $0x29
DATA c41b<>+24(SB)/1, $0x29
DATA c41b<>+25(SB)/1, $0x29
DATA c41b<>+26(SB)/1, $0x29
DATA c41b<>+27(SB)/1, $0x29
DATA c41b<>+28(SB)/1, $0x29
DATA c41b<>+29(SB)/1, $0x29
DATA c41b<>+30(SB)/1, $0x29
DATA c41b<>+31(SB)/1, $0x29
GLOBL c41b<>(SB), RODATA|NOPTR, $32

