//go:build ppc64le

package base32

import "golang.org/x/sys/cpu"

// hasVSX gates the ppc64le VSX kernels (both encode and decode). The generated
// kernels emit ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X) that raise SIGILL
// on POWER8, so they run only when the CPU is POWER9+; on POWER8 encodeSIMD and
// decodeSIMD report no progress and the stdlib encoding/base32 path does all the
// work. It is a var (not a const) so the dispatch test can force the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

// encodeBlocksVSX (5 bytes -> 8 chars per iteration) is the vectorised base32
// encoder. Generated by go-asmgen (encode_ppc64le_gen.go), in encode_ppc64le.s.
// It emits ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X) that SIGILL on
// POWER8, so callers must gate it behind hasVSX (cpu.PPC64.IsPOWER9).
func encodeBlocksVSX(dst, src []byte, n int)

// encodeSIMD runs the VSX kernel over the part of src where both its 16-byte
// over-reading load (per 5-byte group) and its 16-byte store stay in bounds,
// reporting bytes consumed/written so the caller finishes the tail with
// encoding/base32. Each 5-byte group emits 8 chars but STXVB16X writes a full
// 16-byte vector, so the final group must keep 8 bytes of slack in dst. On a
// pre-POWER9 CPU it reports no progress so the whole input goes to the stdlib.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if !hasVSX || n < 16 {
		return 0, 0
	}
	groups := (n-16)/5 + 1
	// Cap so the last 16-byte store (at dst[(groups-1)*8]) stays in bounds.
	for groups > 0 && (groups-1)*8+16 > len(dst) {
		groups--
	}
	if groups == 0 {
		return 0, 0
	}
	encodeBlocksVSX(dst, src, groups)
	return groups * 5, groups * 8
}
