//go:build arm64

package base32

// encodeBlocksNEON (5 bytes -> 8 chars per iteration) is the vectorised base32
// (RFC 4648 StdEncoding) encoder for arm64 NEON. Generated by go-asmgen
// (encode_arm64_gen.go), in encode_arm64.s. It uses the integer widening
// multiply (VUMULL/VUMULL2), the register-variable shift (VUSHL) and table
// lookup (VTBL), all assembled by the Go 1.27 arm64 assembler — the module's
// floor. NEON is baseline on arm64, so there is no runtime feature dispatch.
func encodeBlocksNEON(dst, src []byte, n int)

// encodeSIMD runs the NEON kernel over the part of src where both its 16-byte
// over-reading load (per 5-byte group) and its 16-byte store stay in bounds,
// reporting bytes consumed/written so the caller finishes the tail with
// encoding/base32. Each 5-byte group emits 8 chars but VST1 writes a full
// 16-byte vector, so the final group must keep 8 bytes of slack in dst.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/5 + 1
	// Cap so the last 16-byte store (at dst[(groups-1)*8]) stays in bounds.
	for groups > 0 && (groups-1)*8+16 > len(dst) {
		groups--
	}
	if groups == 0 {
		return 0, 0
	}
	encodeBlocksNEON(dst, src, groups)
	return groups * 5, groups * 8
}
