//go:build amd64

package base32

import "golang.org/x/sys/cpu"

// encodeBlocksSSE (5 bytes -> 8 chars) and encodeBlocksAVX2 (10 -> 16) are the
// vectorised base32 encoders. Generated by go-asmgen (encode_gen.go), in
// encode_amd64.s.
func encodeBlocksSSE(dst, src []byte, n int)
func encodeBlocksAVX2(dst, src []byte, n int)

var hasAVX2 = cpu.X86.HasAVX2

// encodeSIMD runs the widest available kernel over the part of src where its
// over-reading load stays in bounds, reporting bytes consumed/written so the
// caller finishes the tail. The SSE path reads 16 bytes per 5-byte group; the
// AVX2 path loads two 128-bit lanes (src+0 and src+5) so it reads 21 bytes per
// 10-byte pair-of-groups.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if hasAVX2 && n >= 21 {
		groups := (n-21)/10 + 1
		encodeBlocksAVX2(dst, src, groups)
		return groups * 10, groups * 16
	}
	if n >= 16 {
		groups := (n-16)/5 + 1
		encodeBlocksSSE(dst, src, groups)
		return groups * 5, groups * 8
	}
	return 0, 0
}
