// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·encodeBlocksVX(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	MOVD $shuf<>(SB), R4
	VL (R4), V8
	MOVD $mul<>(SB), R4
	VL (R4), V9
	MOVD $pack<>(SB), R4
	VL (R4), V10
	MOVD $c25<>(SB), R4
	VL (R4), V11
	MOVD $c65<>(SB), R4
	VL (R4), V12
	MOVD $c41<>(SB), R4
	VL (R4), V13
	MOVD $mask1f<>(SB), R4
	VL (R4), V14
	CMPBEQ R3, $0, done
loop:
	VL (R2), V0
	VPERM V0, V0, V8, V1
	VMLHH V1, V9, V1
	VPERM V1, V1, V10, V4
	VN V4, V14, V4
	VCHLB V4, V11, V5
	VN V5, V13, V5
	VAB V4, V12, V4
	VSB V5, V4, V4
	VST V4, (R1)
	ADD $5, R2
	ADD $8, R1
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	RET

DATA shuf<>+0(SB)/1, $0x00
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x00
DATA shuf<>+3(SB)/1, $0x01
DATA shuf<>+4(SB)/1, $0x01
DATA shuf<>+5(SB)/1, $0x01
DATA shuf<>+6(SB)/1, $0x01
DATA shuf<>+7(SB)/1, $0x02
DATA shuf<>+8(SB)/1, $0x02
DATA shuf<>+9(SB)/1, $0x03
DATA shuf<>+10(SB)/1, $0x03
DATA shuf<>+11(SB)/1, $0x03
DATA shuf<>+12(SB)/1, $0x03
DATA shuf<>+13(SB)/1, $0x04
DATA shuf<>+14(SB)/1, $0x04
DATA shuf<>+15(SB)/1, $0x04
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA mul<>+0(SB)/1, $0x00
DATA mul<>+1(SB)/1, $0x20
DATA mul<>+2(SB)/1, $0x04
DATA mul<>+3(SB)/1, $0x00
DATA mul<>+4(SB)/1, $0x00
DATA mul<>+5(SB)/1, $0x80
DATA mul<>+6(SB)/1, $0x10
DATA mul<>+7(SB)/1, $0x00
DATA mul<>+8(SB)/1, $0x02
DATA mul<>+9(SB)/1, $0x00
DATA mul<>+10(SB)/1, $0x00
DATA mul<>+11(SB)/1, $0x40
DATA mul<>+12(SB)/1, $0x08
DATA mul<>+13(SB)/1, $0x00
DATA mul<>+14(SB)/1, $0x01
DATA mul<>+15(SB)/1, $0x00
GLOBL mul<>(SB), RODATA|NOPTR, $16

DATA pack<>+0(SB)/1, $0x01
DATA pack<>+1(SB)/1, $0x03
DATA pack<>+2(SB)/1, $0x05
DATA pack<>+3(SB)/1, $0x07
DATA pack<>+4(SB)/1, $0x09
DATA pack<>+5(SB)/1, $0x0b
DATA pack<>+6(SB)/1, $0x0d
DATA pack<>+7(SB)/1, $0x0f
DATA pack<>+8(SB)/1, $0x00
DATA pack<>+9(SB)/1, $0x00
DATA pack<>+10(SB)/1, $0x00
DATA pack<>+11(SB)/1, $0x00
DATA pack<>+12(SB)/1, $0x00
DATA pack<>+13(SB)/1, $0x00
DATA pack<>+14(SB)/1, $0x00
DATA pack<>+15(SB)/1, $0x00
GLOBL pack<>(SB), RODATA|NOPTR, $16

DATA mask1f<>+0(SB)/1, $0x1f
DATA mask1f<>+1(SB)/1, $0x1f
DATA mask1f<>+2(SB)/1, $0x1f
DATA mask1f<>+3(SB)/1, $0x1f
DATA mask1f<>+4(SB)/1, $0x1f
DATA mask1f<>+5(SB)/1, $0x1f
DATA mask1f<>+6(SB)/1, $0x1f
DATA mask1f<>+7(SB)/1, $0x1f
DATA mask1f<>+8(SB)/1, $0x1f
DATA mask1f<>+9(SB)/1, $0x1f
DATA mask1f<>+10(SB)/1, $0x1f
DATA mask1f<>+11(SB)/1, $0x1f
DATA mask1f<>+12(SB)/1, $0x1f
DATA mask1f<>+13(SB)/1, $0x1f
DATA mask1f<>+14(SB)/1, $0x1f
DATA mask1f<>+15(SB)/1, $0x1f
GLOBL mask1f<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA c65<>+0(SB)/1, $0x41
DATA c65<>+1(SB)/1, $0x41
DATA c65<>+2(SB)/1, $0x41
DATA c65<>+3(SB)/1, $0x41
DATA c65<>+4(SB)/1, $0x41
DATA c65<>+5(SB)/1, $0x41
DATA c65<>+6(SB)/1, $0x41
DATA c65<>+7(SB)/1, $0x41
DATA c65<>+8(SB)/1, $0x41
DATA c65<>+9(SB)/1, $0x41
DATA c65<>+10(SB)/1, $0x41
DATA c65<>+11(SB)/1, $0x41
DATA c65<>+12(SB)/1, $0x41
DATA c65<>+13(SB)/1, $0x41
DATA c65<>+14(SB)/1, $0x41
DATA c65<>+15(SB)/1, $0x41
GLOBL c65<>(SB), RODATA|NOPTR, $16

DATA c41<>+0(SB)/1, $0x29
DATA c41<>+1(SB)/1, $0x29
DATA c41<>+2(SB)/1, $0x29
DATA c41<>+3(SB)/1, $0x29
DATA c41<>+4(SB)/1, $0x29
DATA c41<>+5(SB)/1, $0x29
DATA c41<>+6(SB)/1, $0x29
DATA c41<>+7(SB)/1, $0x29
DATA c41<>+8(SB)/1, $0x29
DATA c41<>+9(SB)/1, $0x29
DATA c41<>+10(SB)/1, $0x29
DATA c41<>+11(SB)/1, $0x29
DATA c41<>+12(SB)/1, $0x29
DATA c41<>+13(SB)/1, $0x29
DATA c41<>+14(SB)/1, $0x29
DATA c41<>+15(SB)/1, $0x29
GLOBL c41<>(SB), RODATA|NOPTR, $16

