// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·encodeBlocksVSX(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $shuf<>(SB), R6
	LXVB16X (R6), VS40
	MOVD $shcnt<>(SB), R6
	LXVB16X (R6), VS41
	MOVD $pack<>(SB), R6
	LXVB16X (R6), VS42
	MOVD $c25<>(SB), R6
	LXVB16X (R6), VS43
	MOVD $c65<>(SB), R6
	LXVB16X (R6), VS44
	MOVD $c41<>(SB), R6
	LXVB16X (R6), VS45
	MOVD $mask1f<>(SB), R6
	LXVB16X (R6), VS46
	CMP R5, $0
	BEQ done
loop:
	LXVB16X (R4), VS32
	VPERM V0, V0, V8, V1
	VSRH V1, V9, V1
	VPERM V1, V1, V10, V4
	VAND V4, V14, V4
	VCMPGTUB V4, V11, V5
	VAND V5, V13, V5
	VADDUBM V4, V12, V4
	VSUBUBM V4, V5, V4
	STXVB16X VS36, (R3)
	ADD $5, R4
	ADD $8, R3
	ADD $-1, R5
	CMP R5, $0
	BNE loop
done:
	RET

DATA shuf<>+0(SB)/1, $0x00
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x00
DATA shuf<>+3(SB)/1, $0x01
DATA shuf<>+4(SB)/1, $0x01
DATA shuf<>+5(SB)/1, $0x01
DATA shuf<>+6(SB)/1, $0x01
DATA shuf<>+7(SB)/1, $0x02
DATA shuf<>+8(SB)/1, $0x02
DATA shuf<>+9(SB)/1, $0x03
DATA shuf<>+10(SB)/1, $0x03
DATA shuf<>+11(SB)/1, $0x03
DATA shuf<>+12(SB)/1, $0x03
DATA shuf<>+13(SB)/1, $0x04
DATA shuf<>+14(SB)/1, $0x04
DATA shuf<>+15(SB)/1, $0x04
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA shcnt<>+0(SB)/1, $0x0b
DATA shcnt<>+1(SB)/1, $0x0b
DATA shcnt<>+2(SB)/1, $0x06
DATA shcnt<>+3(SB)/1, $0x06
DATA shcnt<>+4(SB)/1, $0x09
DATA shcnt<>+5(SB)/1, $0x09
DATA shcnt<>+6(SB)/1, $0x04
DATA shcnt<>+7(SB)/1, $0x04
DATA shcnt<>+8(SB)/1, $0x07
DATA shcnt<>+9(SB)/1, $0x07
DATA shcnt<>+10(SB)/1, $0x0a
DATA shcnt<>+11(SB)/1, $0x0a
DATA shcnt<>+12(SB)/1, $0x05
DATA shcnt<>+13(SB)/1, $0x05
DATA shcnt<>+14(SB)/1, $0x08
DATA shcnt<>+15(SB)/1, $0x08
GLOBL shcnt<>(SB), RODATA|NOPTR, $16

DATA pack<>+0(SB)/1, $0x01
DATA pack<>+1(SB)/1, $0x03
DATA pack<>+2(SB)/1, $0x05
DATA pack<>+3(SB)/1, $0x07
DATA pack<>+4(SB)/1, $0x09
DATA pack<>+5(SB)/1, $0x0b
DATA pack<>+6(SB)/1, $0x0d
DATA pack<>+7(SB)/1, $0x0f
DATA pack<>+8(SB)/1, $0x00
DATA pack<>+9(SB)/1, $0x00
DATA pack<>+10(SB)/1, $0x00
DATA pack<>+11(SB)/1, $0x00
DATA pack<>+12(SB)/1, $0x00
DATA pack<>+13(SB)/1, $0x00
DATA pack<>+14(SB)/1, $0x00
DATA pack<>+15(SB)/1, $0x00
GLOBL pack<>(SB), RODATA|NOPTR, $16

DATA mask1f<>+0(SB)/1, $0x1f
DATA mask1f<>+1(SB)/1, $0x1f
DATA mask1f<>+2(SB)/1, $0x1f
DATA mask1f<>+3(SB)/1, $0x1f
DATA mask1f<>+4(SB)/1, $0x1f
DATA mask1f<>+5(SB)/1, $0x1f
DATA mask1f<>+6(SB)/1, $0x1f
DATA mask1f<>+7(SB)/1, $0x1f
DATA mask1f<>+8(SB)/1, $0x1f
DATA mask1f<>+9(SB)/1, $0x1f
DATA mask1f<>+10(SB)/1, $0x1f
DATA mask1f<>+11(SB)/1, $0x1f
DATA mask1f<>+12(SB)/1, $0x1f
DATA mask1f<>+13(SB)/1, $0x1f
DATA mask1f<>+14(SB)/1, $0x1f
DATA mask1f<>+15(SB)/1, $0x1f
GLOBL mask1f<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA c65<>+0(SB)/1, $0x41
DATA c65<>+1(SB)/1, $0x41
DATA c65<>+2(SB)/1, $0x41
DATA c65<>+3(SB)/1, $0x41
DATA c65<>+4(SB)/1, $0x41
DATA c65<>+5(SB)/1, $0x41
DATA c65<>+6(SB)/1, $0x41
DATA c65<>+7(SB)/1, $0x41
DATA c65<>+8(SB)/1, $0x41
DATA c65<>+9(SB)/1, $0x41
DATA c65<>+10(SB)/1, $0x41
DATA c65<>+11(SB)/1, $0x41
DATA c65<>+12(SB)/1, $0x41
DATA c65<>+13(SB)/1, $0x41
DATA c65<>+14(SB)/1, $0x41
DATA c65<>+15(SB)/1, $0x41
GLOBL c65<>(SB), RODATA|NOPTR, $16

DATA c41<>+0(SB)/1, $0x29
DATA c41<>+1(SB)/1, $0x29
DATA c41<>+2(SB)/1, $0x29
DATA c41<>+3(SB)/1, $0x29
DATA c41<>+4(SB)/1, $0x29
DATA c41<>+5(SB)/1, $0x29
DATA c41<>+6(SB)/1, $0x29
DATA c41<>+7(SB)/1, $0x29
DATA c41<>+8(SB)/1, $0x29
DATA c41<>+9(SB)/1, $0x29
DATA c41<>+10(SB)/1, $0x29
DATA c41<>+11(SB)/1, $0x29
DATA c41<>+12(SB)/1, $0x29
DATA c41<>+13(SB)/1, $0x29
DATA c41<>+14(SB)/1, $0x29
DATA c41<>+15(SB)/1, $0x29
GLOBL c41<>(SB), RODATA|NOPTR, $16

