//go:build ppc64le

package base32

// encodeBlocksVSX (5 bytes -> 8 chars per iteration) is the vectorised base32
// encoder for POWER8+ VSX. Generated by go-asmgen (encode_ppc64le_gen.go), in
// encode_ppc64le.s. VSX is baseline on ppc64le, so there is no runtime dispatch.
func encodeBlocksVSX(dst, src []byte, n int)

// encodeSIMD runs the VSX kernel over the part of src where both its 16-byte
// over-reading load (per 5-byte group) and its 16-byte store stay in bounds,
// reporting bytes consumed/written so the caller finishes the tail with
// encoding/base32. Each 5-byte group emits 8 chars but STXVB16X writes a full
// 16-byte vector, so the final group must keep 8 bytes of slack in dst.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/5 + 1
	// Cap so the last 16-byte store (at dst[(groups-1)*8]) stays in bounds.
	for groups > 0 && (groups-1)*8+16 > len(dst) {
		groups--
	}
	if groups == 0 {
		return 0, 0
	}
	encodeBlocksVSX(dst, src, groups)
	return groups * 5, groups * 8
}
