// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64 && go1.27

#include "textflag.h"

TEXT ·encodeBlocksNEON(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $spread<>(SB), R3
	VLD1 (R3), [V8.B16]
	MOVD $mul<>(SB), R3
	VLD1 (R3), [V9.B16]
	MOVD $pack<>(SB), R3
	VLD1 (R3), [V10.B16]
	MOVD $sh<>(SB), R3
	VLD1 (R3), [V11.B16]
	MOVD $mask1f<>(SB), R3
	VLD1 (R3), [V12.B16]
	MOVD $alphalo<>(SB), R3
	VLD1 (R3), [V13.B16]
	MOVD $alphahi<>(SB), R3
	VLD1 (R3), [V14.B16]
	CBZ R2, done
loop:
	VLD1 (R1), [V0.B16]
	VTBL V8.B16, [V0.B16], V1.B16
	VUMULL V9.H4, V1.H4, V20.S4
	VUMULL2 V9.H8, V1.H8, V21.S4
	VUSHL V11.S4, V20.S4, V20.S4
	VUSHL V11.S4, V21.S4, V21.S4
	VXTN V20.S4, V2.H4
	VXTN2 V21.S4, V2.H8
	VAND V12.B16, V2.B16, V2.B16
	VTBL V10.B16, [V2.B16], V3.B16
	VTBL V3.B16, [V13.B16, V14.B16], V4.B16
	VST1 [V4.B16], (R0)
	ADD $5, R1
	ADD $8, R0
	SUB $1, R2
	CBNZ R2, loop
done:
	RET

DATA spread<>+0(SB)/1, $0x00
DATA spread<>+1(SB)/1, $0x00
DATA spread<>+2(SB)/1, $0x01
DATA spread<>+3(SB)/1, $0x00
DATA spread<>+4(SB)/1, $0x01
DATA spread<>+5(SB)/1, $0x01
DATA spread<>+6(SB)/1, $0x02
DATA spread<>+7(SB)/1, $0x01
DATA spread<>+8(SB)/1, $0x03
DATA spread<>+9(SB)/1, $0x02
DATA spread<>+10(SB)/1, $0x03
DATA spread<>+11(SB)/1, $0x03
DATA spread<>+12(SB)/1, $0x04
DATA spread<>+13(SB)/1, $0x03
DATA spread<>+14(SB)/1, $0x04
DATA spread<>+15(SB)/1, $0x04
GLOBL spread<>(SB), RODATA|NOPTR, $16

DATA mul<>+0(SB)/1, $0x20
DATA mul<>+1(SB)/1, $0x00
DATA mul<>+2(SB)/1, $0x00
DATA mul<>+3(SB)/1, $0x04
DATA mul<>+4(SB)/1, $0x80
DATA mul<>+5(SB)/1, $0x00
DATA mul<>+6(SB)/1, $0x00
DATA mul<>+7(SB)/1, $0x10
DATA mul<>+8(SB)/1, $0x00
DATA mul<>+9(SB)/1, $0x02
DATA mul<>+10(SB)/1, $0x40
DATA mul<>+11(SB)/1, $0x00
DATA mul<>+12(SB)/1, $0x00
DATA mul<>+13(SB)/1, $0x08
DATA mul<>+14(SB)/1, $0x00
DATA mul<>+15(SB)/1, $0x01
GLOBL mul<>(SB), RODATA|NOPTR, $16

DATA pack<>+0(SB)/1, $0x00
DATA pack<>+1(SB)/1, $0x02
DATA pack<>+2(SB)/1, $0x04
DATA pack<>+3(SB)/1, $0x06
DATA pack<>+4(SB)/1, $0x08
DATA pack<>+5(SB)/1, $0x0a
DATA pack<>+6(SB)/1, $0x0c
DATA pack<>+7(SB)/1, $0x0e
DATA pack<>+8(SB)/1, $0x1f
DATA pack<>+9(SB)/1, $0x1f
DATA pack<>+10(SB)/1, $0x1f
DATA pack<>+11(SB)/1, $0x1f
DATA pack<>+12(SB)/1, $0x1f
DATA pack<>+13(SB)/1, $0x1f
DATA pack<>+14(SB)/1, $0x1f
DATA pack<>+15(SB)/1, $0x1f
GLOBL pack<>(SB), RODATA|NOPTR, $16

DATA sh<>+0(SB)/1, $0xf0
DATA sh<>+1(SB)/1, $0xf0
DATA sh<>+2(SB)/1, $0xf0
DATA sh<>+3(SB)/1, $0xf0
DATA sh<>+4(SB)/1, $0xf0
DATA sh<>+5(SB)/1, $0xf0
DATA sh<>+6(SB)/1, $0xf0
DATA sh<>+7(SB)/1, $0xf0
DATA sh<>+8(SB)/1, $0xf0
DATA sh<>+9(SB)/1, $0xf0
DATA sh<>+10(SB)/1, $0xf0
DATA sh<>+11(SB)/1, $0xf0
DATA sh<>+12(SB)/1, $0xf0
DATA sh<>+13(SB)/1, $0xf0
DATA sh<>+14(SB)/1, $0xf0
DATA sh<>+15(SB)/1, $0xf0
GLOBL sh<>(SB), RODATA|NOPTR, $16

DATA mask1f<>+0(SB)/1, $0x1f
DATA mask1f<>+1(SB)/1, $0x1f
DATA mask1f<>+2(SB)/1, $0x1f
DATA mask1f<>+3(SB)/1, $0x1f
DATA mask1f<>+4(SB)/1, $0x1f
DATA mask1f<>+5(SB)/1, $0x1f
DATA mask1f<>+6(SB)/1, $0x1f
DATA mask1f<>+7(SB)/1, $0x1f
DATA mask1f<>+8(SB)/1, $0x1f
DATA mask1f<>+9(SB)/1, $0x1f
DATA mask1f<>+10(SB)/1, $0x1f
DATA mask1f<>+11(SB)/1, $0x1f
DATA mask1f<>+12(SB)/1, $0x1f
DATA mask1f<>+13(SB)/1, $0x1f
DATA mask1f<>+14(SB)/1, $0x1f
DATA mask1f<>+15(SB)/1, $0x1f
GLOBL mask1f<>(SB), RODATA|NOPTR, $16

DATA alphalo<>+0(SB)/1, $0x41
DATA alphalo<>+1(SB)/1, $0x42
DATA alphalo<>+2(SB)/1, $0x43
DATA alphalo<>+3(SB)/1, $0x44
DATA alphalo<>+4(SB)/1, $0x45
DATA alphalo<>+5(SB)/1, $0x46
DATA alphalo<>+6(SB)/1, $0x47
DATA alphalo<>+7(SB)/1, $0x48
DATA alphalo<>+8(SB)/1, $0x49
DATA alphalo<>+9(SB)/1, $0x4a
DATA alphalo<>+10(SB)/1, $0x4b
DATA alphalo<>+11(SB)/1, $0x4c
DATA alphalo<>+12(SB)/1, $0x4d
DATA alphalo<>+13(SB)/1, $0x4e
DATA alphalo<>+14(SB)/1, $0x4f
DATA alphalo<>+15(SB)/1, $0x50
GLOBL alphalo<>(SB), RODATA|NOPTR, $16

DATA alphahi<>+0(SB)/1, $0x51
DATA alphahi<>+1(SB)/1, $0x52
DATA alphahi<>+2(SB)/1, $0x53
DATA alphahi<>+3(SB)/1, $0x54
DATA alphahi<>+4(SB)/1, $0x55
DATA alphahi<>+5(SB)/1, $0x56
DATA alphahi<>+6(SB)/1, $0x57
DATA alphahi<>+7(SB)/1, $0x58
DATA alphahi<>+8(SB)/1, $0x59
DATA alphahi<>+9(SB)/1, $0x5a
DATA alphahi<>+10(SB)/1, $0x32
DATA alphahi<>+11(SB)/1, $0x33
DATA alphahi<>+12(SB)/1, $0x34
DATA alphahi<>+13(SB)/1, $0x35
DATA alphahi<>+14(SB)/1, $0x36
DATA alphahi<>+15(SB)/1, $0x37
GLOBL alphahi<>(SB), RODATA|NOPTR, $16

